Source/CarthageKit/Xcode.swift

Switch to relative symlinks between build folders

---

Source/CarthageKit/Project.swift
Source/CarthageKit/Xcode.swift
Source/CarthageKitTests/XcodeSpec.swift
Source/carthage/Build.swift
Source/carthage/Update.swift

Add --platform flag to limit a build

---

README.md

_Depends on #302._
Resolves #10.

Document how to automatically rebuild dependencies

---

README.md

Add a few lines about transitive dependencies

---

Source/CarthageKit/Project.swift

Fix duplicate repository fetching when using ref pins

---

Source/CarthageKit/GitHub.swift
Source/CarthageKit/Project.swift

Much better than enumerating all of them!

Fetch GitHub Releases by specific tag

---

Source/CarthageKit/FrameworkExtensions.swift
Source/CarthageKit/GitHub.swift
Source/CarthageKit/Xcode.swift

Fix RACError.Empty for private repository checkouts

---

Carthage.xcodeproj/project.pbxproj
Source/CarthageKit/Archive.swift
Source/CarthageKit/FrameworkExtensions.swift
Source/CarthageKit/Xcode.swift
Source/CarthageKitTests/ArchiveSpec.swift
Source/CarthageKitTests/XcodeSpec.swift
Source/carthage/Archive.swift
Source/carthage/main.swift

Resolves #258.
```
justin:ReactiveCocoa/ (git)-[master] $ carthage archive ReactiveCocoa
*** Found Carthage/Build/Mac/ReactiveCocoa.framework
*** Found Carthage/Build/iOS/ReactiveCocoa.framework
*** Created ReactiveCocoa.framework.zip
```

Add `carthage archive` for packaging releases

---

README.md

Describe how to add a Carthage badge to a README

---

Source/CarthageKit/Xcode.swift

Hopefully fixes #347. :pray:
**To do:**

Don't pass in -sdk macosx

---

Source/CarthageKit/GitHub.swift
Source/CarthageKit/Xcode.swift

Issue #234: suggest GitHub issue when no shared schemes in GitHub repository

---

Carthage.xcodeproj/project.pbxproj
Source/CarthageKit/FileSink.swift
Source/CarthageKitTests/FileSinkSpec.swift
Source/carthage/Build.swift

Encapsulate log streaming in a FileSink type

---

Source/CarthageKit/Git.swift

Use a refspec when fetching existing submodules

---

Source/carthage/Build.swift

Only when not running verbosely, since `--verbose` will get you all that output by default anyways.
Resolves #216.

grep for and forward error-like messages from Xcode

---

Source/CarthageKit/Resolver.swift

Just an optimization I noticed while investigating other issues.
Before this change, we were creating graph permutations for the _original_ nodes passed in, even though our `graph.addNode` calls might result in a tightening of those nodes' constraints. The effect was that we could end up creating graphs that we already know to be impossible.
This uses the nodes _after_ their constraints have been tightened, so we only explore paths that may result in something valid.

Tighten version constraints for graph permutations

---

Source/CarthageKit/Project.swift

Since `self.cachedVersions[project]` was always `nil` when there are no tags, we would always try re-fetching the affected project.
Confusingly, this does _not_ fix https://github.com/Carthage/Carthage/issues/448, since the affected project in that example does indeed have tags.

Fix multiple fetches for projects without tags

---

Source/CarthageKit/Xcode.swift

The filtering by UTI that is currently being done excludes symlinks to projects from being considered for scheme discovery. Considering that scheme search is limited to the first project being found in lexicographical order, symlinks can be an important tool to make sure Carthage sees the "right" project.

Treat symlinks to projects like regular projects.

---

Source/CarthageKit/GitHub.swift

Use `flatMap` and nil coalescing operator to remove a `var` declaration and `if clause` checking for nil.

Refactored `userAgent` closure

---

Source/CarthageKit/GitHub.swift
Source/CarthageKitTests/DuplicateDependencies/Cartfile

Use case insensitive comparison for GitHub repository names

---

Source/CarthageKit/GitHub.swift

Currently, Carthage uses the `browser_url` field on a GitHub release asset to download precompiled binaries. However, when downloading a private binary, this URL only succeeds if the user is logged into their GitHub account on Safari. This is because the cookies are shared between Safari and Carthage, and thus the browser URL request is successful because the user is already authenticated. As such, If the user is **not** logged into their GitHub account in Safari, the download fails with an opaque error stating that the release zip file is invalid. When you inspect the contents of the downloaded file in the `~/Libarary/Caches/org.carthage.CarthageKit/binaries/` directory, the contents of the file are the string "Not Found", rather than the zipped `.framework` that you'd expect.
To rememdy …

Fix release downloads by using GitHub API rather than browser URL

---

Makefile

Resolves https://github.com/Homebrew/homebrew/pull/40450#issuecomment-109534187.

Don't add an @rpath that's already set

---

Source/CarthageKit/Xcode.swift
Source/carthage/Build.swift

Support for watchOS builds

---

README.md

In support of #536, per @jspahrsummers’s request

Mentioned xcode-select

---

Source/CarthageKit/Resolver.swift

This project is already Swift 1.2 compatible.

Use native Set type in Resolver

---

Source/CarthageKit/Project.swift
Source/CarthageKit/Resolver.swift
Source/CarthageKit/Xcode.swift
Source/CarthageKitTests/ArchiveSpec.swift
Source/CarthageKitTests/ResolverSpec.swift
Source/CarthageKitTests/XcodeSpec.swift
Source/carthage/Archive.swift

Now is the time. See https://github.com/Carthage/Carthage/pull/368#discussion_r29791444.

Put collect() operator in its place

---

.gitignore
CONTRIBUTING.md

This addresses a concern raised in Issue #564

Added a section to the CONTRIBUTING.md about opening the project

---

Documentation/Artifacts.md

Add remote branch example

---

Source/CarthageKit/GitHub.swift

I'm sorry for the late action to #605. :sweat_smile:

Minor refactoring for optional binding

---

Source/CarthageKit/Git.swift
Source/CarthageKit/GitHub.swift

Hopefully fixes https://github.com/Carthage/Carthage/issues/219#issuecomment-109992121.

Set `GIT_TERMINAL_PROMPT=0` for all git tasks

---

Source/CarthageKit/Project.swift

Resolves https://github.com/Carthage/Carthage/issues/431#issuecomment-127588964.

Accept binary frameworks of pre-release versions

---

Source/carthage/Archive.swift

Include dSYMS when archiving built frameworks

---

Documentation/Artifacts.md
README.md

The main thing I want to make sure of here is that there is enough context to understand what this feature is for.
This is just the first thing I came up with — open to any kind of feedback!

Add a section to the README about using dSYM files

---

Source/CarthageKit/Xcode.swift

Looks at `SUPPORTED_PLATFORMS` instead of `PLATFORM_NAME` to decide for which platforms to build.
Fixes #340

Support universal framework targets.

---

README.md

[README] Prebuilt frameworks of prerelease versions are not ignored now

---

Documentation/Artifacts.md
Source/CarthageKit/Cartfile.swift
Source/CarthageKit/GitHub.swift
Source/CarthageKit/Project.swift
Source/CarthageKitTests/CartfileSpec.swift
Source/CarthageKitTests/ResolverSpec.swift
Source/CarthageKitTests/TestCartfile

Add support for GitHub Enterprise

---

README.md

Addresses #616 and https://github.com/Carthage/Carthage/issues/680#issuecomment-131314816.

[README] iOS application targets also have the “Embedded Binaries” section in their build settings

---

Source/CarthageKit/Project.swift
Source/carthage/Bootstrap.swift
Source/carthage/Update.swift

Implement --no-checkout flag for bootstrap/update commands

---

Source/CarthageKit/Git.swift
Source/CarthageKit/Project.swift

Should fix #694, #642 and #407.

If a directory in repository caches is not a valid repository, remove that directory then clone the project

---

Source/carthage/Build.swift

This approach may be safer than what was previously written.

Safer optional chaining, fix for somewhat dangerous if-let  

---

README.md

[README] Refer to `archive` command

---

Source/carthage/Version.swift

This may be a slightly more stable way to phrase this section.
Hope it helps!

remove needless optional cast

---

Source/CarthageKit/Xcode.swift

Thought this might be a simpler way to achieve the same thing. 
Hope it helps!

More concise phrasing for ProjectLocator description.

---

Source/CarthageKit/FrameworkExtensions.swift

I tried to simplify this part to one if-let with a where clause testing for the same thing the outer if did.
Hope it helps!

Replace nested if statement with where clause

---

Source/carthage/Formatting.swift

Thought that this formatting increases human readability.
Hope it helps!

fix formatting

---

Source/carthage/Build.swift

Shorten NSComparisonResult cases

---

Source/CarthageKitTests/XcodeSpec.swift
Source/carthage/Build.swift

Some minor cleanup for #583. :bow:

Follow up to #583

---

Source/CarthageKit/Git.swift

I thought this may be a more straight forward and compact way to go about these checks. 
Hope it helps!

Simpler name and directory check

---

Source/CarthageKit/Xcode.swift
Source/carthage/Build.swift

I've tested this with https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2333

Added support for tvOS

---

Source/CarthageKitTests/XcodeSpec.swift

Addresses https://github.com/Carthage/Carthage/pull/766#issuecomment-141671784. This PR is submitted from my forked repo to confirm that the build ends successfully.

Works around the test failure in CI environment

---

Source/CarthageKit/Xcode.swift

Fixes #776. The behavior was changed in #583.

Restore per-platform SDKs handling

---

Source/CarthageKit/Cartfile.swift

Sorry for the nit-pick but I thought this might read a little cleaner.
Tests passed, build runs clean.
Hope it helps!

More direct way of returning string description.

---

Source/CarthageKit/Xcode.swift

Resolves #535, many thanks to the discussion in that issue! :sparkling_heart:

Support embedding bitcode when ENABLE_BITCODE=YES

---

Source/CarthageKit/Project.swift
Source/CarthageKit/Xcode.swift
Source/carthage/CopyFrameworks.swift

Extracts the common logic into `copyFileURLsFromProducer()` function.

Refactor copying bcsymbolmap files and others

---

Source/CarthageKit/Git.swift

- `substringToIndex()` -> `subscript()`
- `Range<String.Index>` based `enumerateSubstringsInRange()`

Use String APIs, not NSString ones

---

Source/CarthageKit/Project.swift
Source/CarthageKit/Xcode.swift
Source/carthage/CopyFrameworks.swift

As per @kballard's comment: https://github.com/Carthage/Carthage/pull/874#discussion_r43556939
Surely this seems better.

Implement copyFileURLsIntoDirectory() as a producer extension method

---

README.md

Update Readme for homebrew installation

---

Source/carthage/Build.swift

Add “OSX” alias for --platform option

---

Source/CarthageKit/Errors.swift
Source/CarthageKit/Xcode.swift
Source/CarthageKitTests/XcodeSpec.swift

Starting to clean things up a bit.

Clean up Xcode data types

---

Source/CarthageKit/Git.swift
Source/carthage/main.swift

Resolves #774. How do you feel about the implementation?

Ensure that required git version is used

---

README.md

- Small addition to the README in order to document how to setup travis releases

Documentation for travis-ci framework uploads

---

Carthage.xcodeproj/project.pbxproj
Documentation/BashZshFishCompletion.md
README.md
Source/Scripts/carthage-fish-completion

This pull request adds auto completion of Carthage commands and options for the [fish shell](http://fishshell.com).

Fish completions

---

Source/carthage/Archive.swift
Source/carthage/Bootstrap.swift
Source/carthage/Build.swift
Source/carthage/Checkout.swift
Source/carthage/CopyFrameworks.swift
Source/carthage/Fetch.swift
Source/carthage/Update.swift
Source/carthage/Version.swift

Those can be inferred from the method signatures.

Specify concrete `Options` type instead of explicit `typealias`es

---

Source/CarthageKit/FrameworkExtensions.swift
Source/CarthageKit/GitHub.swift
Source/CarthageKit/Project.swift
Source/CarthageKit/Resolver.swift
Source/CarthageKit/Version.swift
Source/CarthageKit/Xcode.swift

https://github.com/apple/swift-evolution/blob/master/proposals/0003-remove-var-parameters-patterns.md

Avoid var binding which will be removed in Swift 3.0

---

Source/carthage/Archive.swift
Source/carthage/Bootstrap.swift
Source/carthage/Build.swift
Source/carthage/Checkout.swift
Source/carthage/Fetch.swift
Source/carthage/Update.swift

I thought this would make the relationship between the `CommandType` and the `OptionsType` clearer.

Make all Options structs into inner structs

---

Source/CarthageKitTests/ArchiveSpec.swift
Source/CarthageKitTests/CartfileSpec.swift
Source/CarthageKitTests/FrameworkExtensionsSpec.swift
Source/CarthageKitTests/ProjectSpec.swift
Source/CarthageKitTests/VersionSpec.swift
Source/CarthageKitTests/XcodeSpec.swift

The same as https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2618.

[Specs] Replace some Nimble matchers with equivalent operators

---

Source/CarthageKitTests/FrameworkExtensionsSpec.swift
Source/CarthageKitTests/XcodeSpec.swift

Cleanup a few things from #892

---

Source/Scripts/carthage-bash-completion
Source/Scripts/carthage-fish-completion
Source/Scripts/carthage-zsh-completion

Update completion scripts

---

Source/CarthageKit/Xcode.swift

Accept "BNDL" value of `CFBundlePackageType` in `binaryURL`

---

README.md

Since dependencies can be updated individually.

Update "Upgrading frameworks" section

---

Source/CarthageKit/Xcode.swift
Source/CarthageKitTests/XcodeSpec.swift

Skip "Carthage/Checkouts", not "Carthage" directory

---

Source/CarthageKit/Errors.swift
Source/CarthageKit/Resolver.swift

Improve the message of CarthageError.IncompatibleRequirements

---

Carthage.xcodeproj/project.pbxproj
Source/CarthageKit/Resolver.swift
Source/CarthageKitTests/ResolverSpec.swift
Source/CarthageKitTests/TestCartfileProposedVersion

Permit dependency nodes match those have incompatible version specifiers, but have the same proposed version

---

Source/CarthageKit/Project.swift

Fixes #1107. This is missed in #1100. :sweat_smile:

Skip unspecified dependencies in buildOrderForResolvedCartfile

---

Source/CarthageKit/Xcode.swift

Addresses https://github.com/Carthage/Carthage/pull/1071#discussion_r51324564.

Use SignalProducer.replayLazily for multicasting in buildInDirectory

---

Source/CarthageKit/Git.swift

Added `gitRootDirectoryForRepository` method to get the root of the repo and used this path in `submodulesInRepository` to get the Submodules info.

Fixes: 1063, Run ls-tree in repo root instead of current directory

---

Source/CarthageKit/Git.swift

As per Issue #1145, `rev-parse --show-toplevel` will fail (return empty path) when ran inside a bare repo, which caused `gitRootDirectoryForRepository` to return invalid root path (empty string)
Modified `gitRootDirectoryForRepository` to return repo path as it is if its bare, else return what `rev-parse --show-toplevel` says.
I've tested this with `github thoughtbot/Argo` and `github antitypical/Result`, working fine in both cases. 
But, for `github Mantle/Mantle` it is picking very old versions of `Nimble`, causing build failure.
Could somebody please confirm?

Check for bare repo when running --show-toplevel

---

README.md

This is intended to address https://github.com/Carthage/Carthage/issues/1079

Clarify where build script should be added

---

Source/CarthageKit/Xcode.swift

This will hopefully fix #1163 for those folks that are hitting the timeout.

Double the xcodebuild -showBuildSettings timeout

---

Source/CarthageIntegration/archive.bats
Source/CarthageIntegration/update.bats

Fix integration tests

---

Source/CarthageKit/Git.swift
Source/CarthageKit/Project.swift
Source/CarthageKitTests/ProjectSpec.swift

Correctly fetch repository when the specified git object is a branch

---

Source/carthage/CopyFrameworks.swift

Instead of copying frameworks to
${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}, copy them to
${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}.
This fixes `carthage copy-frameworks` for unit test targets in
Xcode 7.3, and should be fully backwards compatible as well (i.e., both
paths mentioned above should resolve to the same paths in older Xcode
versions.)
Fixes #1203.

Copy frameworks to ${TARGET_BUILD_DIR}

---

Source/CarthageKit/FrameworkExtensions.swift
Source/CarthageKit/Git.swift
Source/CarthageKit/Project.swift
Source/CarthageKit/Resolver.swift

Fixes #1237
We should treat tags as immutable. I should have caught this in code review.

Only fetch for branches, not tags

---

Source/CarthageIntegration/update.bats
Source/CarthageKit/Cartfile.swift
Source/CarthageKitTests/CartfileSpec.swift

Fix Cartfile.resolved outputs for GitHub origin

---

Source/carthage/Archive.swift

Addresses https://github.com/Carthage/Carthage/pull/1251#discussion_r59134080. :sparkles:

Extract outputPathWithOptions into a free function

---

Source/CarthageIntegration/copy-frameworks.bats
Source/carthage/CopyFrameworks.swift

Fix copy-frameworks when archiving

---

Source/CarthageKit/Errors.swift
Source/carthage/Bootstrap.swift

Minor tweaks for Bootstrap.swift

---

Source/CarthageKit/Git.swift
Source/CarthageKit/GitHub.swift
Source/CarthageKit/Project.swift
Source/CarthageKit/Resolver.swift
Source/CarthageKit/Xcode.swift
Source/carthage/Build.swift

This should have been done in #1329. 😅

Remove unnecessary `promoteErrors`s

---

Source/Scripts/carthage-zsh-completion

Updated zsh completion file.
Thanks.

Add support for completion dependency name with zsh

---

Source/CarthageKit/Project.swift
Source/CarthageKit/Xcode.swift

I did this on the plane the other day. ☺️

Refactor parts of Project.swift and Xcode.swift

---

Source/CarthageKit/Project.swift

Fixes #1366 by reverting part of #1353.

Don't require Cartfile.private

---

Source/carthage/Archive.swift

Make archive command use options.directoryPath to look for frameworks

---

Source/CarthageKit/Xcode.swift

Strip “Headers” directory in copy-frameworks

---

Source/Scripts/carthage-bash-completion
Source/Scripts/carthage-fish-completion
Source/Scripts/carthage-zsh-completion
Source/carthage/Build.swift

[carthage] Accept `macOS` for `--platform` option

---

.travis.yml
Makefile

xctool won't support Xcode 8 and will be deprecated. See https://github.com/facebook/xctool/issues/704 for the details.

Use plain xcodebuild instead of xctool

---

Carthage.xcodeproj/project.pbxproj
Source/CarthageKit/BuildOptions.swift
Source/CarthageKit/Project.swift
Source/CarthageKit/Xcode.swift
Source/CarthageKitTests/XcodeSpec.swift
Source/carthage/Build.swift
Source/carthage/Update.swift

Arose in https://github.com/Carthage/Carthage/pull/1057#issuecomment-177572209 and https://github.com/Carthage/Carthage/pull/1057#issuecomment-177612122.

Add BuildOptions to share common options between `build` and `update` commands

---

README.md

Readme is updated with respective note about embedded framework.

#1427 README upd: link dependencies from embedded frameworks to the app target

---

Source/Scripts/carthage-bash-completion
Source/Scripts/carthage-fish-completion
Source/Scripts/carthage-zsh-completion

Update completion for
- Bash
- Zsh
- Fish
because carthage has new commands and options that isn't included in current completions.

Update shell completion

---

Source/CarthageKit/Xcode.swift

Fixes #1360.
For schemes that built multiple targets, Carthage was building the scheme multiple times. This is because we’d read the build settings for the scheme, separate the settings by target, and build any buildable targets by building the scheme. Since building the scheme builds all the targets inside, this was redundant.
This fixes the issue by `collect`ing the settings and then flattening them after the scheme is built.

Eliminate redundant builds

---

Source/CarthageKit/GitHub.swift

I thought using map here might be a little more brief.
How does it look?
Thanks!

Code simplification using map.

---

README.md

Hi,
I saw this comment: https://github.com/Carthage/Carthage/issues/924#issuecomment-256187029
So I tried to fix it.
🍎🍎🍎

Update README's Known issues section

---

.travis.yml
README.md
Source/CarthageKit/FrameworkExtensions.swift
Source/CarthageKit/GitHub.swift

Drop Swift 2.2 / Xcode 7.3 support

---

Source/CarthageKitTests/ArchiveSpec.swift
Source/CarthageKitTests/CartfileSpec.swift
Source/CarthageKitTests/ProjectSpec.swift
Source/CarthageKitTests/ResolverSpec.swift
Source/CarthageKitTests/XcodeSpec.swift

[swift3-prep] Replace `dynamicType` with `type(of:)`

---

Source/CarthageKit/Archive.swift
Source/CarthageKit/Cartfile.swift
Source/CarthageKit/Errors.swift
Source/CarthageKit/FrameworkExtensions.swift
Source/CarthageKit/Git.swift
Source/CarthageKit/GitHub.swift
Source/CarthageKit/Project.swift
Source/CarthageKit/Resolver.swift
Source/CarthageKit/Version.swift
Source/CarthageKit/Xcode.swift
Source/CarthageKitTests/ProjectSpec.swift
Source/CarthageKitTests/ResolverSpec.swift
Source/CarthageKitTests/XcodeSpec.swift
Source/carthage/Archive.swift
Source/carthage/Bootstrap.swift
Source/carthage/Build.swift
Source/carthage/BuildVersion.swift
Source/carthage/CopyFrameworks.swift
Source/carthage/Environment.swift
Source/carthage/Update.swift

[swift3-prep][CarthageError] Make enum cases lowerCamelCase

---

Source/CarthageKit/Xcode.swift
Source/CarthageKitTests/BuildArgumentsSpec.swift
Source/carthage/Archive.swift
Source/carthage/Formatting.swift

- `BitcodeGenerationMode`
- `ProductType`
- `MachOType`
- `FrameworkType`
- `PackageType`
- `ColorArgument`

[swift3-prep] Make enum cases lowerCamelCase

---

Source/CarthageKit/Project.swift
Source/CarthageKitTests/ProjectSpec.swift
Source/carthage/Build.swift
Source/carthage/Extensions.swift

[swift3-prep][ProjectEvent] Make enum cases lowerCamelCase

---

Source/CarthageKit/BuildArguments.swift
Source/CarthageKit/Xcode.swift
Source/CarthageKitTests/BuildArgumentsSpec.swift
Source/CarthageKitTests/XcodeSpec.swift

[swift3-prep][ProjectLocator] Make enum cases lowerCamelCase

---

Source/CarthageKit/Cartfile.swift
Source/CarthageKit/Errors.swift
Source/CarthageKit/Project.swift
Source/CarthageKit/Xcode.swift
Source/CarthageKitTests/CartfileSpec.swift
Source/CarthageKitTests/ProjectSpec.swift
Source/CarthageKitTests/ResolverSpec.swift
Source/CarthageKitTests/XcodeSpec.swift
Source/carthage/Archive.swift
Source/carthage/Fetch.swift

[swift3-prep][ProjectIdentifier] Make enum cases lowerCamelCase

---

Source/CarthageKit/Resolver.swift
Source/CarthageKit/Version.swift
Source/CarthageKitTests/CartfileSpec.swift
Source/CarthageKitTests/VersionSpec.swift

[swift3-prep][VersionSpecifier] Make enum cases lowerCamelCase

---

Carthage.xcodeproj/project.pbxproj
Source/CarthageKit/Archive.swift
Source/CarthageKit/Cartfile.swift
Source/CarthageKit/FrameworkExtensions.swift
Source/CarthageKit/Git.swift
Source/CarthageKit/GitHub.swift
Source/CarthageKit/Project.swift
Source/CarthageKit/Resolver.swift
Source/CarthageKit/Swift3Shims.swift
Source/CarthageKit/Version.swift
Source/CarthageKit/Xcode.swift
Source/CarthageKitTests/ResolverSpec.swift
Source/carthage/Build.swift
Source/carthage/CopyFrameworks.swift
Source/carthage/Environment.swift
Source/carthage/Version.swift

[swift3-prep] Add `Result.success` and `Result.failure` shims

---

Source/CarthageKit/Archive.swift
Source/CarthageKit/Git.swift
Source/CarthageKit/Project.swift
Source/CarthageKit/Swift3Shims.swift
Source/CarthageKit/Xcode.swift
Source/CarthageKitTests/XcodeSpec.swift
Source/carthage/Build.swift

[swift3-prep] Add ReactiveTask shims

---

Source/CarthageKit/FrameworkExtensions.swift
Source/CarthageKit/Git.swift
Source/CarthageKit/ProducerQueue.swift
Source/CarthageKit/Project.swift
Source/CarthageKit/Resolver.swift
Source/CarthageKit/Swift3Shims.swift
Source/CarthageKit/Xcode.swift
Source/carthage/Build.swift
Source/carthage/BuildVersion.swift
Source/carthage/Checkout.swift
Source/carthage/CopyFrameworks.swift
Source/carthage/Extensions.swift
Source/carthage/Outdated.swift

#1558 
Based on [the file](https://github.com/ReactiveCocoa/ReactiveSwift/blob/bac956ee3e93dcad0b5528009362502ec91257c8/Sources/Deprecations%2BRemovals.swift).

[swift3-prep] Add ReactiveSwift shims

---

Source/CarthageKit/Archive.swift
Source/CarthageKit/FrameworkExtensions.swift
Source/CarthageKit/Git.swift
Source/CarthageKit/GitHub.swift
Source/CarthageKit/ProducerQueue.swift
Source/CarthageKit/Project.swift
Source/CarthageKit/Resolver.swift
Source/CarthageKit/Swift3Shims.swift
Source/CarthageKit/Xcode.swift
Source/CarthageKitTests/XcodeSpec.swift
Source/carthage/Archive.swift
Source/carthage/Bootstrap.swift
Source/carthage/Build.swift
Source/carthage/Checkout.swift
Source/carthage/CopyFrameworks.swift
Source/carthage/Outdated.swift
Source/carthage/Update.swift

[swift3-prep] Add FlattenStrategy shims

---

Source/carthage/Update.swift

Disable binary downloads if `--toolchain` option is given

---

Source/CarthageKit/GitHub.swift
Source/CarthageKit/Project.swift
Source/CarthageKit/Swift3Shims.swift
Source/CarthageKit/Xcode.swift
Source/CarthageKitTests/ArchiveSpec.swift
Source/CarthageKitTests/CartfileSpec.swift
Source/CarthageKitTests/ProjectSpec.swift
Source/CarthageKitTests/ResolverSpec.swift
Source/CarthageKitTests/XcodeSpec.swift
Source/carthage/BuildVersion.swift
Source/carthage/Version.swift
Source/carthage/main.swift

[swift3-prep] Add Foundation.Bundle shims

---

Source/CarthageKit/FrameworkExtensions.swift
Source/CarthageKit/Git.swift
Source/CarthageKit/Project.swift
Source/CarthageKit/Swift3Shims.swift
Source/CarthageKit/Xcode.swift
Source/CarthageKitTests/ArchiveSpec.swift
Source/CarthageKitTests/FrameworkExtensionsSpec.swift
Source/CarthageKitTests/ProjectSpec.swift
Source/CarthageKitTests/XcodeSpec.swift
Source/carthage/Archive.swift
Source/carthage/Bootstrap.swift
Source/carthage/Build.swift
Source/carthage/Checkout.swift
Source/carthage/Outdated.swift

[swift3-prep] Add Foundation.FileManager shims

---

Source/CarthageKit/Git.swift
Source/CarthageKit/Project.swift
Source/CarthageKit/Swift3Shims.swift
Source/CarthageKit/Version.swift
Source/CarthageKit/Xcode.swift
Source/CarthageKitTests/ProjectSpec.swift

[swift3-prep] Add Foundation.CharacterSet shims

---

Source/CarthageKit/GitHub.swift
Source/CarthageKit/Swift3Shims.swift
Source/CarthageKit/Xcode.swift

[swift3-prep] Add NSRegularExpression and NSTextCheckingResult shims

---

Source/CarthageKit/Cartfile.swift
Source/CarthageKit/Git.swift
Source/CarthageKit/Swift3Shims.swift
Source/carthage/Build.swift
Source/carthage/Environment.swift

[swift3-prep] Add Foundation.ComparisonResult shims

---

Source/CarthageKit/Cartfile.swift
Source/CarthageKit/FrameworkExtensions.swift
Source/CarthageKit/Git.swift
Source/CarthageKit/Scannable.swift
Source/CarthageKit/Swift3Shims.swift
Source/CarthageKit/Version.swift
Source/CarthageKit/Xcode.swift

[swift3-prep] Add Foundation.Scanner shims

---

Source/CarthageKit/Git.swift
Source/CarthageKit/Swift3Shims.swift
Source/CarthageKit/Xcode.swift
Source/carthage/Build.swift

#1558 
- `Data`
- `Date`
- `FileHandle`

[swift3-prep] Add some Foundation shims

---

Source/CarthageKit/Git.swift
Source/CarthageKit/GitHub.swift
Source/CarthageKit/Project.swift
Source/CarthageKit/Swift3Shims.swift
Source/CarthageKitTests/ArchiveSpec.swift
Source/CarthageKitTests/ProjectSpec.swift
Source/CarthageKitTests/XcodeSpec.swift
Source/carthage/Environment.swift

[swift3-prep] Add Foundation.ProcessInfo shims

---

Source/CarthageKit/Project.swift
Source/CarthageKit/Swift3Shims.swift
Source/CarthageKit/Xcode.swift

[swift3-prep] Add Foundation.UUID shims

---

Source/CarthageKit/Project.swift
Source/CarthageKit/Xcode.swift

[swift3-prep] Rename some missing FlattenStrategy values

---

Source/CarthageKit/GitHub.swift
Source/CarthageKit/Project.swift
Source/CarthageKit/Swift3Shims.swift
Source/CarthageKitTests/CartfileSpec.swift
Source/carthage/BuildVersion.swift

#1558 and https://github.com/mdiep/Tentacle/pull/49

[swift3-prep] Add Tentacle shims

---

Carthage.xcodeproj/project.pbxproj
Source/CarthageKit/Archive.swift
Source/CarthageKit/Availability.swift
Source/CarthageKit/Project.swift
Source/CarthageKitTests/ArchiveSpec.swift
Source/carthage/Archive.swift

[CarthageKit/Archive.swift] Adopt API Design Guidelines

---

Source/CarthageKit/Availability.swift
Source/CarthageKit/Git.swift
Source/CarthageKitTests/XcodeSpec.swift
Source/carthage/Build.swift
Source/carthage/Formatting.swift
Source/carthage/Outdated.swift
Source/carthage/Update.swift

[swift3-prep] Add `is` prefix to some Bool variables

---

Source/CarthageKit/Cartfile.swift
Source/CarthageKit/Errors.swift
Source/CarthageKit/Git.swift
Source/CarthageKit/Resolver.swift
Source/CarthageKit/Version.swift
Source/carthage/Archive.swift
Source/carthage/Build.swift
Source/carthage/Checkout.swift
Source/carthage/Fetch.swift
Source/carthage/Formatting.swift
Source/carthage/Outdated.swift
Source/carthage/Update.swift

- #1558 
- https://github.com/apple/swift-evolution/blob/master/proposals/0066-standardize-function-type-syntax.md

[swift3-prep] Adopt SE-0066

---

Source/CarthageKit/Swift3Shims.swift
Source/carthage/Formatting.swift

[swift3-prep] Add PrettyColors shims

---

Source/CarthageKit/Archive.swift
Source/CarthageKit/Availability.swift
Source/CarthageKit/BuildArguments.swift
Source/CarthageKit/Cartfile.swift
Source/CarthageKit/Errors.swift
Source/CarthageKit/FrameworkExtensions.swift
Source/CarthageKit/Git.swift
Source/CarthageKit/GitHub.swift
Source/CarthageKit/Project.swift
Source/CarthageKit/Swift3Shims.swift
Source/CarthageKit/Xcode.swift
Source/CarthageKitTests/ArchiveSpec.swift
Source/CarthageKitTests/BuildArgumentsSpec.swift
Source/CarthageKitTests/CartfileSpec.swift
Source/CarthageKitTests/FrameworkExtensionsSpec.swift
Source/CarthageKitTests/ProjectSpec.swift
Source/CarthageKitTests/XcodeSpec.swift
Source/carthage/Archive.swift
Source/carthage/Bootstrap.swift
Source/carthage/Build.swift
Source/carthage/Checkout.swift
Source/carthage/CopyFrameworks.swift
Source/carthage/Outdated.swift

[swift3-prep] Add Foundation.URL shims

---

Source/CarthageKit/Project.swift
Source/CarthageKit/Swift3Shims.swift

Renames `URLForDirectory` and `isWritableFileAtPath`.

[swift3-prep] Add missing Foundation.FileManager shims

---

Source/CarthageKit/Algorithms.swift
Source/CarthageKit/BuildArguments.swift
Source/CarthageKit/Errors.swift
Source/CarthageKit/Git.swift
Source/CarthageKit/GitHub.swift
Source/CarthageKit/Project.swift
Source/CarthageKit/Resolver.swift
Source/CarthageKit/Swift3Shims.swift
Source/CarthageKit/Version.swift
Source/CarthageKit/Xcode.swift
Source/carthage/Archive.swift
Source/carthage/Bootstrap.swift
Source/carthage/Build.swift
Source/carthage/Extensions.swift
Source/carthage/Update.swift

[swift3-prep] Add (some) Sequence and Collection shims

---

Source/CarthageKit/Archive.swift
Source/CarthageKit/BuildArguments.swift
Source/CarthageKit/Cartfile.swift
Source/CarthageKit/FrameworkExtensions.swift
Source/CarthageKit/GitHub.swift
Source/CarthageKit/Project.swift
Source/CarthageKit/Swift3Shims.swift
Source/CarthageKit/Xcode.swift
Source/CarthageKitTests/ArchiveSpec.swift
Source/CarthageKitTests/ProjectSpec.swift
Source/CarthageKitTests/XcodeSpec.swift
Source/carthage/Archive.swift
Source/carthage/Build.swift

[swift3-prep] Add Foundation.NSString shims

---

Source/CarthageKit/FrameworkExtensions.swift

[swift3-prep] Rename `permuteWith(_:)` to `permute(with:)`

---

Source/CarthageKit/Cartfile.swift
Source/CarthageKit/Scannable.swift
Source/CarthageKit/Version.swift
Source/carthage/BuildVersion.swift

[CarthageKit/Scannable] Adopt API Design Guidelines

---

Source/CarthageKit/Cartfile.swift
Source/CarthageKit/Git.swift
Source/CarthageKit/GitHub.swift
Source/CarthageKit/Project.swift
Source/CarthageKit/Swift3Shims.swift
Source/CarthageKit/Xcode.swift
Source/CarthageKitTests/ArchiveSpec.swift
Source/CarthageKitTests/CartfileSpec.swift
Source/CarthageKitTests/ProjectSpec.swift
Source/CarthageKitTests/ResolverSpec.swift
Source/CarthageKitTests/XcodeSpec.swift
Source/carthage/Bootstrap.swift
Source/carthage/Build.swift
Source/carthage/CopyFrameworks.swift
Source/carthage/Formatting.swift
Source/carthage/Update.swift

[swift3-prep] Add String shims

---

Source/CarthageKit/Availability.swift
Source/CarthageKit/Cartfile.swift
Source/CarthageKit/Project.swift
Source/CarthageKit/Resolver.swift
Source/CarthageKitTests/CartfileSpec.swift
Source/CarthageKitTests/ResolverSpec.swift

[CarthageKit/Cartfile.swift] Adopt API Design Guidelines

---

Carthage.xcodeproj/project.pbxproj
Source/CarthageKit/Platform.swift
Source/CarthageKit/Xcode.swift
Source/CarthageKitTests/ProjectLocatorSpec.swift
Source/CarthageKitTests/XcodeSpec.swift

Extract `ProjectLocatorSpec` as well which is missed in #1661.

Extract Platform into its own file

---

Source/CarthageKit/BuildSettings.swift
Source/CarthageKit/FrameworkExtensions.swift
Source/CarthageKit/Git.swift
Source/CarthageKit/Project.swift
Source/CarthageKit/Swift3Shims.swift
Source/CarthageKit/Xcode.swift

[swift3-prep] Add missing Foundation shims

---

Source/CarthageKit/BuildSettings.swift
Source/CarthageKit/Project.swift
Source/CarthageKit/Resolver.swift
Source/CarthageKit/Swift3Shims.swift
Source/CarthageKit/Xcode.swift
Source/CarthageKitTests/ResolverSpec.swift
Source/carthage/Archive.swift
Source/carthage/Build.swift
Source/carthage/CopyFrameworks.swift

#1558 and https://github.com/ReactiveCocoa/ReactiveSwift/pull/120

[swift3-prep] Add `SignalProducer.init` shims

---

Source/CarthageKit/Cartfile.swift
Source/CarthageKit/Version.swift
Source/CarthageKitTests/CartfileSpec.swift

This fits with the actual intention of the property.

Use a Set for Cartfile.dependencies

---

Source/CarthageKit/Swift3Shims.swift
Source/CarthageKit/Xcode.swift

[swift3-prep] Add missing TaskEvent shims

---

Source/CarthageKit/BuildSettings.swift
Source/CarthageKit/Swift3Shims.swift
Source/CarthageKit/Xcode.swift

#1558 and https://github.com/antitypical/Result/pull/204

[swift3-prep] Add `Result.fanout` shim

---

Source/CarthageKit/Availability.swift
Source/CarthageKit/BuildSettings.swift
Source/CarthageKit/ProductType.swift

[CarthageKit/ProductType.swift] Adopt API Design Guidelines

---

Source/CarthageKit/Cartfile.swift
Source/CarthageKit/Project.swift
Source/CarthageKitTests/CartfileSpec.swift

Sort Cartfile.resolved

---

Source/carthage/Archive.swift
Source/carthage/Build.swift
Source/carthage/Checkout.swift
Source/carthage/Extensions.swift
Source/carthage/Fetch.swift
Source/carthage/Formatting.swift
Source/carthage/Outdated.swift
Source/carthage/Update.swift

[swift3-prep] Add Commandant shims

---

Source/CarthageKit/Availability.swift
Source/CarthageKit/BuildSettings.swift
Source/CarthageKit/Project.swift
Source/CarthageKit/SDK.swift

[CarthageKit/SDK.swift] Adopt API Design Guidelines

---

README.md

Need to make it clearer that bootstrap exists and for whom it is useful.
As per #1709

Added a header

---

Source/CarthageKitTests/ResolverSpec.swift

I want to start building up more tests cases before I actually try to fix any.

Add pending (i.e. failing) test for #1707

---

Source/CarthageKit/FrameworkExtensions.swift
Source/CarthageKit/Swift3Shims.swift

[swift3-prep][URL] Add `carthage_...` property shims in Swift 3

---

Source/CarthageKit/Swift3Shims.swift
Source/carthage/Archive.swift
Source/carthage/Bootstrap.swift
Source/carthage/Build.swift
Source/carthage/Checkout.swift
Source/carthage/CopyFrameworks.swift
Source/carthage/Extensions.swift
Source/carthage/Fetch.swift
Source/carthage/Formatting.swift
Source/carthage/Outdated.swift
Source/carthage/Update.swift
Source/carthage/Version.swift

[swift3-prep] Add Commandant shims for protocol names

---

Source/CarthageKit/Cartfile.swift
Source/CarthageKit/Errors.swift
Source/CarthageKit/Git.swift
Source/CarthageKit/Project.swift
Source/CarthageKit/Version.swift
Source/carthage/Build.swift

https://github.com/Carthage/Carthage/pull/1762/files?w=1

[gardening] Move operators into types

---

Makefile

Calculate the pkg version from git

---

Source/carthage/BuildVersion.swift
Source/carthage/main.swift

Ignore draft releases for the new Carthage release check

---

Source/carthage/Build.swift
Source/carthage/Update.swift

closes #1860
depends on https://github.com/mdiep/Tentacle/issues/68

Add support for custom log paths.

---

Source/CarthageKitTests/XcodeSpec.swift

As mentioned in #1755 
Fixes tests in #1866 
@jdhealy, thanks!

Remove hardcoding of swift version in tests.

---

Source/CarthageKit/Project.swift
Source/CarthageKit/VersionFile.swift
Source/CarthageKit/Xcode.swift
Source/CarthageKitTests/XcodeSpec.swift

https://github.com/Carthage/Carthage/pull/1835#issue-214999237

Reduce Dependency type usages

---

.travis.yml
Carthage.xcodeproj/project.pbxproj
Makefile
Package.pins
Package.swift
Tests/CarthageKitTests/XcodeSpec.swift
script/copy-fixtures

Since SwiftPM creates a test bundle on macOS,
- Let SwiftPM just build the test bundle without running it
- Copy test resources into the bundle
- Finally run the test bundle

[CI] Run `swift test`

---

Source/CarthageKit/Archive.swift

Add `-uo` option to `unzip` command

---

.travis.yml

Looks like somehow this would fix #2033. 😕 
https://travis-ci.org/Carthage/Carthage/builds/249125244

[Travis] Remove an unused secure variable

---

Source/CarthageKit/Project.swift
Tests/CarthageKitTests/ProjectSpec.swift

Fixes #2034 
This attempts to read the Cartfile from the current source checkout first (except during 'update' resolution) before falling back to the current git cache read/fetch.

Use checked out cartfile

---

Source/CarthageKit/Xcode.swift

Fixes #2026 
In the new build system, a clean will delete the entire build folder rather than just the build objects. This only affects us when we try to build a device/simulator in a row, then merge the executables. Since they are two different sdks and architectures, they will be using different build subdirectories anyway, I made it so we only clean on the first of the 2 builds. In all other situations we still always clean.
Actual logic change is in the first commit, second commit just moves a rather large closure definition into its own method

Avoid clean between sdks

---

.swiftlint.yml
Source/CarthageKit/Algorithms.swift
Source/CarthageKit/BinaryProject.swift
Source/CarthageKit/Cartfile.swift
Source/CarthageKit/Errors.swift
Source/CarthageKit/Git.swift
Source/CarthageKit/Project.swift
Source/CarthageKit/VersionFile.swift
Source/CarthageKit/Xcode.swift
Source/XCDBLD/ProjectLocator.swift
Tests/.swiftlint.yml

It seems to me that the rule makes the readability worse.

[SwiftLint] Remove `single_line_guard` custom rule

---

Source/CarthageKit/BuildSettings.swift
Source/CarthageKit/FrameworkExtensions.swift
Source/CarthageKit/GitHub.swift
Source/CarthageKit/Xcode.swift

https://developer.apple.com/documentation/foundation/nstextcheckingresult/1416732-range

Add `NSTextCheckingResult.range(at:)` shim to prepare for Xcode 9

---

Source/CarthageKit/VersionFile.swift

One more real simple no-functional-change refactor while I’m at it.

[gardening] Postpone unneeded optional until after `reduce`

---

Source/CarthageKit/Git.swift

Mostly non-functional, straight refactoring — I'll point out the few functional changes in comments…

[gardening] Refactor `cloneSubmoduleInWorkingDirectory` with `attemptMap`.

---

Tests/XCDBLDTests/XcodeVersionSpec.swift
XCDBLD.xcodeproj/project.pbxproj

Add tests for XcodeVersion

---

Source/CarthageKit/Archive.swift

This should solve https://github.com/Carthage/Carthage/issues/2091

Add Bzip2 support for carthage

---

Makefile

I met a guy, he downloaded the carthage zip file from github, then double-clicked the Makefile file because Makefile was executable.  Leads to remove all non-synstem file. e.g. `rm -rf "$(FRAMEWORKS_FOLDER)/$(OUTPUT_FRAMEWORK)"` will interpret as `rm -rf /` .

[Makefile] Use variables for specifying repeated commands

---

Tests/CarthageKitTests/ResolverSpec.swift

[ResolverSpec] Add some examples to a pending test

---

.travis.yml
Cartfile.private
Cartfile.resolved
Tests/CarthageKitTests/ResolverSpec.swift

Introduced in https://github.com/Quick/Quick/pull/701.
Please see the diff: https://github.com/Carthage/Carthage/pull/2135/files?w=1

Update Quick and use the `Behavior`

---

Source/CarthageKit/BinaryProject.swift
Tests/CarthageKitTests/BinaryProjectSpec.swift

[BinaryProject] Add `file` scheme support

---

Source/carthage/Build.swift

This should be simpler operation.

[gardening][BuildCommand] Use `loadResolvedCartfile` over `loadCombinedCartfile`

---

Source/CarthageKit/Algorithms.swift
Source/CarthageKit/Project.swift
Tests/CarthageKitTests/ProjectSpec.swift

[gardening] Replace `forEach` with for-in loop

---

Source/CarthageKit/GitHub.swift
Source/carthage/Build.swift

https://github.com/apple/swift-evolution/blob/master/proposals/0171-reduce-with-inout.md

[gardening] Utilize `reduce(into:)`

---

Makefile
Package.swift

https://github.com/apple/swift-package-manager/blob/swift-4.0-branch/Documentation/PackageDescriptionV4.md

[SwiftPM] Use V4 PackageDescription

---

Source/CarthageKit/BuildSettings.swift

Such projects have unexpected `CONFIGURATION_BUILD_DIR` build setting which is appending a target name to a common `CONFIGURATION_BUILD_DIR` value. That is problematic for our path building.
The issue is found at https://github.com/AliSoftware/Reusable/issues/50#issuecomment-336434345.
Ref: #2158

Fix CocoaPods-generated projects support when running `archive` action

---

README.md

Add README info about `outdated --xcode-warnings`

---

README.md

Realized I never included an update to the Readme in my original PR

Update readme to mention the new resolver flag

---

Source/CarthageKit/Git.swift
Source/CarthageKit/Project.swift

Reverts Carthage/Carthage#2125
Ref: #2185

Revert "Fix fetching a local repository with relative path"

---

Tests/CarthageKitTests/ResolverSpec.swift
Tests/CarthageKitTests/XcodeSpec.swift

https://github.com/Quick/Nimble#writing-your-own-matchers

[Nimble] Migrate to Predicate API

---

RELEASE.md

Document how to create a release

---

ISSUE_TEMPLATE.md

Add some more fields to issue template:
- Carthage install method (something might be wrong with the packaging)
- `which carthage`, the location of the binary might make people realize they are not using the binary they intended to use
- Add --new-resolver filed (some people might not know this is an option)
- Ask to describe what happened and what they expect should happen

Improve Issue Template

---

README.md

Addressing change request form #2335 . 
Should it be italic (see: https://github.com/Carthage/Carthage/pull/2335#issuecomment-360536871) or is this enough?

Minor fixes - Address change request

---

Source/CarthageKit/BuildOptions.swift
Source/CarthageKit/Project.swift
Source/carthage/Build.swift
Source/carthage/Checkout.swift
Source/carthage/Update.swift

As titled. It got more straightforward✨
Resolves: https://github.com/Carthage/Carthage/issues/2308
Related: https://github.com/Carthage/Carthage/pull/2317#issuecomment-362600637

Move binary download to build process

---

Source/CarthageKit/Project.swift
Tests/CarthageKitTests/ProjectSpec.swift

This fixes #2188. 
I have essentially no experience with ReactiveSwift, so chances are there improvements that can be made to this. 
I haven't taken a look at the tests yet, but I can add some if needed. I should have time later this week for it.

Update X's dependencies when running carthage update X.

---

Carthage.xcodeproj/project.pbxproj
Source/CarthageKit/GitHub.swift
Source/CarthageKit/Proxy.swift
Source/carthage/BuildVersion.swift
Tests/CarthageKitTests/ProxyTests.swift

Completes PR #1996, which resolves #1682.

Add support for proxied environments

---

Source/CarthageKit/VersionFile.swift

Hi!. Fixed swiftlint comma warnings in VersionFile.swift

Fix swiftlint comma warnings

---

RELEASE.md

Update RELEASE.md homebrew release process documentation

Update RELEASE.md homebrew release process documentation

---

README.md

Add notice to run chown on /usr/local

---

README.md

- Add TOC
- Add quick start
- Rearrange some sections
This is just an idea, comments welcome. Check [here](https://github.com/blender/Carthage/blob/feature/TOC/README.md)

[README] Add Table of Contents and others

---

README.md

Fix install instructions link

---

Tests/CarthageKitTests/CartfileSpec.swift
Tests/CarthageKitTests/Resources/TestCartfile
Tests/CarthageKitTests/VersionSpec.swift

See comment in https://github.com/Carthage/Carthage/pull/2412#pullrequestreview-122235889

Add test for non-semver reference with number sign

---

.github/stale.yml

Addresses #2503 
also added:
- "help wanted" tag to excludes

Add config for StaleBot https://github.com/apps/stale

---

Source/CarthageKit/Cartfile.swift
Source/CarthageKit/MachHeader.swift
Source/CarthageKit/Project.swift
Source/CarthageKit/Version.swift
Source/CarthageKit/VersionFile.swift
Source/carthage/CopyFrameworks.swift

This will reduce the unnecessary diffs in #2519.

[SwiftLint] Run `$ swiftlint autocorrect`

---

Source/CarthageKit/Xcode.swift

Replacing `collect()` and `isEmpty` check with `take(first: 1)`.

Refactor `buildScheme` a bit

---

Source/carthage/CopyFrameworks.swift

Fixes https://github.com/Carthage/Carthage/issues/2589
In Xcode 10, we can declare the script phase' input/output file using an xcfilelist file.
But `carthage copy-framework` command has not supported xcfilelist style declaration. Because `copy-framework` sub-command does not recognize `SCRIPT_OUTPUT_FILE_LIST_COUNT` and `SCRIPT_OUTPUT_FILE_LIST_(#)` parameters.
With this PR, `copy-frameworks` can recognize `SCRIPT_INPUT_FILE_LIST_COUNT` and `SCRIPT_INPUT_FILE_LIST_(#)` used in `xcfilelist` and treat each line as an input file.
See also:
https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes/build_system_release_notes_for_xcode_10
> xcfilelist file with resolved build setting references will be provided in the SCRIPT_INPUT_FILE_LIST_(#) and …

Add support for `*.xcfilelist` file in copy-frameworks

---

Carthage.xcodeproj/project.pbxproj
Documentation/Artifacts.md
Source/CarthageKit/GitHub.swift
Tests/CarthageKitTests/GitHubSpec.swift

Ref: https://github.com/Carthage/Carthage/issues/2379#issuecomment-374428450 and https://github.com/Carthage/Carthage/issues/2379#issuecomment-374456138
Closes #2379.

[BREAKING][Cartfile] Reject `git` or `ssh` protocol as a `github` origin as it does not make sense

---

Source/carthage/CopyFrameworks.swift

@kishikawakatsumi added support of file lists to copy frameworks script. I have updated wording to reflect these changes.

Update function and error for copy frameworks to reflect file lists support

---

Source/CarthageKit/Simulator.swift

This PR addresses code style changes in `Simulator` decoding discussed with @giginet in #2630.

Update code style in Simulator decoding

---

Source/carthage/Archive.swift

To my understanding this PR should address #2641

[Issue #2641] Delete zip archive before creating a new one

---

Source/CarthageKit/Git.swift

This fixes an error if you try to switch to using submodules.
```
» carthage checkout
*** Checking out Result at "4.0.0"
» carthage checkout --use-submodules
*** Checking out Result at "4.0.0"
A shell task (/usr/bin/env git clone --quiet /Users/mdiep/Library/Caches/org.carthage.CarthageKit/dependencies/Result Carthage/Checkouts/Result) failed with exit code 128:
fatal: destination path 'Carthage/Checkouts/Result' already exists and is not an empty directory.
» carthage-dev checkout --use-submodules
*** Checking out Result at "4.0.0"
```

Remove existing items before git cloning submodules

---

Source/carthage/CopyFrameworks.swift

When one of the files specified in the `SCRIPT_INPUT_FILE_LIST_@` envvars is not readable, the `copy-frameworks` command fails with the following unhelpful error:
```
Could not cast value of type 'NSError' (...) to 'Result.NoError' (...).
```
This PR fixes this issue and now Carthage displays the `readFailed` error.

Show error when input file list is not readable

---

Source/CarthageKit/Simulator.swift
Tests/CarthageKitTests/Resources/Simulators/availables-xcode101-beta.json
Tests/CarthageKitTests/Resources/Simulators/availables-xcode101.json
Tests/CarthageKitTests/Resources/Simulators/availables-xcode102-beta.json
Tests/CarthageKitTests/Resources/Simulators/availables.json
Tests/CarthageKitTests/Resources/Simulators/unavailable.json
Tests/CarthageKitTests/SimulatorSpec.swift

re: https://github.com/Carthage/Carthage/issues/2691
This implementation could probably use some finesse, but hopefully it's of some use.

Add Xcode 10.2 beta simulator support

---

README.md

MacPorts also provides [a package](https://www.macports.org/ports.php?by=library&substr=carthage).

Mention MacPorts in README

---

Source/CarthageKit/GitHub.swift
Tests/CarthageKitTests/GitHubSpec.swift

Pass the Authorization header across to the redirected request

---

Source/CarthageKit/Git.swift

Use ssh batch mode so git doesn't attempt to prompt the user and hang.

---

Source/CarthageKit/Xcode.swift

This is meant to resolve an issue with Xcode 10.2 using the new build system where different architectures have conditional blocks in the Swift headers.
Issue: https://github.com/Carthage/Carthage/issues/2718

Add functionality to merge Swift header files

---

Source/CarthageKit/GitHub.swift
Tests/CarthageKitTests/GitHubSpec.swift

Revert passing authorization headers for redirected URLSession requests

---

Source/CarthageKit/BinaryProject.swift
Source/CarthageKit/Project.swift
Source/CarthageKit/Xcode.swift
Source/carthage/CopyFrameworks.swift

Please see each commits for the details.

Address SwiftLint violations

---

.swiftlint.yml

https://github.com/Carthage/Carthage/pull/2765#issuecomment-491802610 😉

[SwiftLint] Add a custom rule to detect possible Carthage typos

---

Source/CarthageKit/Version.swift

Add w character to asciiAlphabeth

---

IntegrationTests/copy-frameworks.bats

https://github.com/ikesyo/CarthageCopyFrameworksFixture/commit/25720a24fab0fde16ff3b77c26b73b3d61fe77fc

Update ikesyo/CarthageCopyFrameworksFixture for compatibility with Xcode 10.2 or above

---

README.md

This addresses: https://github.com/Carthage/Carthage/issues/2897
Here's what the pulldown menu looks like for your reference

Update README guide for Xcode 11 changes

---

README.md

Spell fix for README

---

Source/CarthageKit/CarthageKitVersion.swift

I bumped into the same problem: #3048, and fixed it by updating the version. It would be great if this fix could be applied at your earliest convenience.

Bump up the CarthageKitVersion to 0.35.1

---

Documentation/Xcode12Workaround.md

As #3019 issue contains lot of questions "how can I make this workaround work" I created a page where it is all summarized and can be easily linked, instead of linking to one of 300 comments in the issue.
The script that is contained in the guide is one of the last versions mentioned in the issue and I use it successfully on my projects, so it should be fine to use.

Xcode 12 workaround guide

---

README.md
Source/CarthageKit/CarthageKitVersion.swift
Source/CarthageKit/Xcode.swift

Here's a branch to base the next release off of. I'm not aware of any other code changes we need to make, but @tmspzz let me know if I've missed something :)
Closes #3102, closes #3097

v0.37.0, support for source-based xcframeworks

---

Source/CarthageKit/Xcode.swift

If the architectures argument is empty (because there are no architectures to be stripped), this method will produce and execute an invalid lipo command because it will contain no -remove arguments. To fix this, I make the method a no-op if the input list of architectures is empty.

Fix invalid lipo command in stripArchitectures() when embedding dSYMs

---

ISSUE_TEMPLATE.md

Add one more field to issue template:
- --use-xcframeworks:  which is added at 0.37.0. i think this flag can be the trigger some issues occur or not.

Add: --use-xcframeworks check
