- Source/carthage/CopyFrameworks.swift
Fixes #277:
A bug occurred when calling `carthage help copy-frameworks`. Previously, the CopyFrameworksCommand would ignore the mode argument passed to run() and would attempt to execute the command. This change fixes run() to only execute in Arguments mode.
> Fix copy-frameworks help bug

- Source/carthage/CopyFrameworks.swift
This also avoids map(), which seems to be where the crash is directly occurring.
Hopefully resolves #264.
> Fix `copy-frameworks` segfault

- Makefile
Without this, overriding `TEMPORARY_FOLDER` will only partially work since Xcode always uses `/tmp/Carthage.dst` as its intermediate built products location (see https://developer.apple.com/library/mac/documentation/DeveloperTools/Reference/XcodeBuildSettingRef/1-Build_Setting_Reference/build_setting_ref.html#//apple_ref/doc/uid/TP40003931-CH3-SW22).
Supporting overriding `TEMPORARY_FOLDER` also means that a failed homebrew installation can still clean up temporary artifacts (see https://github.com/Homebrew/homebrew/pull/35926#discussion_r23104627).
I've confirmed this also works with `xctool`.
> Set DSTROOT to TEMPORARY_FOLDER in XCODEFLAGS

- Source/carthage/Build.swift
- Source/carthage/Update.swift
Per #273, the `--verbose` option will print out the xcodebuild log as each build progresses.
- This doesn't (yet) offer a `--verbose` option for `carthage bootstrap` or `carthage update`. I suspect we'll want that option, since a desired use case for verbose output is with `carthage bootstrap` on a non-interactive Travis CI session, but a verbose option on those commands might also print verbose output from the git clone/checkout stage of the process, so I've left it out for the moment.
- My solution for tailing the build log was simply to print each line of data from `stdoutSignal` as it's written to the log file. This appears to correctly interleave the build logs with the non-verbose printing from `schemeSignals`. I have only a beginner's understanding of ReactiveCocoa, so if there's a …
> Build Option: --verbose 

- Source/carthage/Update.swift
Fixes #296.
When git output is written to the log file (#288), that should also be routed according to the `--verbose` option.
> Add --verbose option to Update (and Bootstrap)

- .gitmodules
- Cartfile
- Cartfile.resolved
- Carthage.xcodeproj/project.pbxproj
- Carthage.xcworkspace/contents.xcworkspacedata
- Source/carthage/Bootstrap.swift
- Source/carthage/Build.swift
- Source/carthage/Checkout.swift
- Source/carthage/Components.plist
- Source/carthage/CopyFrameworks.swift
- Source/carthage/Environment.swift
- Source/carthage/Extensions.swift
- Source/carthage/Fetch.swift
- Source/carthage/Formatting.swift
- Source/carthage/Update.swift
_Resolves #121_
Adds colors and formatting to most `carthage.println`s. Imports [jdhealy/PrettyColors](//github.com/jdhealy/PrettyColors).
Basically just the bare minimum of commits to Carthage to allow for flexibility based off your feedback.
I based most of the color and formatting choices off [homebrew](//github.com/homebrew/homebrew).
Output looks like this in iTerm 2 with custom pastel-ish colors:
Output looks like this in Terminal.app using basic colors:
- Color and formatting choices
- Any preferences on colors or formatting?
- I've styled the output so far with [widely-supported styles](https://github.com/jdhealy/PrettyColors/wiki/Terminal-Support) _(bold and underlined)_ and [nearly-universal colors](https://github.com/jdhealy/PrettyColors/blob/development/Source/Color/Named.swift …
> PrettyColors — Take advantage of the terminal

- Cartfile
This already exists in `Cartfile.private`, which is the correct place for it to live according to @jspahrsummers.
See https://twitter.com/jspahrsummers/status/566837562736508928 for a brief explanation.
> Remove xcconfigs from public Cartfile.

- Cartfile
- Cartfile.private
As discussed with @jspahrsummers [on Twitter](https://twitter.com/py/status/566830853997613058).
> Move dependencies for CLI tools into Cartfile.private

- Source/CarthageKit/Archive.swift
- Source/CarthageKitTests/ArchiveSpec.swift
> Include symlinks as-is in `carthage archive`

- Carthage.xcodeproj/project.pbxproj
It’s unclear if this will actually fix any observed issues or not, but we do know that Swift 1.1 is #dangerzone with optimization: https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1632
Resolves #345.
> Disable all Swift optimization for now

- Source/CarthageKit/GitHub.swift
- Source/CarthageKit/Project.swift
GitHub releases allow an empty title.
When the release title is empty, carthage shows
```
*** Downloading ProjectName at ""
```
> Add fallback to show a tag when the release title is empty

- README.md
I added a link to Apple's documentation that shows how to enable Scheme sharing - as the documentation didn't really offer any good advice.
> Added link to directions on how to share a scheme

- Source/CarthageKit/Errors.swift
- Source/CarthageKit/Xcode.swift
Also adds CarthageError.XcodebuildListTimeout. See issue #299.
> When enumerating schemes, increase timeout for `xcodebuild -list` from 4s to 8s

- Source/CarthageKit/Project.swift
- Source/CarthageKit/Xcode.swift
This allows folders in Carthage/Checkouts to be symlinks, if users want to overwrite or otherwise manipulate those folders after `carthage checkout` completes but before `carthage build` runs.
> Fix building in symlinked checkouts

- Source/CarthageKit/GitHub.swift
This was introduced with Git 2.3. My Apple-provided Git is 2.3.2 on my 10.10.3 system with Xcode 6.3.1.
Should fix #449, #447, #445, and #219 on most systems. I’m not sure when or how Apple updates the system Git, so I don’t know which versions won’t be fixed.
> Ask git not to prompt for credentials

- Source/CarthageKit/Project.swift
Resolves #444.
Carthage shouldn't be independently copying nested vendored frameworks.
> Don't count nested frameworks in frameworksInDirectory(_:)

- Source/CarthageKit/Git.swift
e0dfaf9 is the root commit.
Fixes #445, https://github.com/Carthage/Carthage/issues/447#issuecomment-101091446 and #449.
> Fix hanging on cloning or fetching which was introduced from 0.7

- Source/CarthageKit/Xcode.swift
So far, Carthage has been building any schemes that are shown by `xcodebuild -list`, unfortunately, that includes any user schemes as well. This filters the found schemes to those which have a corresponding `.xcscheme` file in the selected project's xcshareddata directory.
> Limit schemes being built to shared ones.

- Source/CarthageKit/Version.swift
- Source/CarthageKitTests/VersionSpec.swift
This means you can have arbitrary, non-version tags that _happen_ to end in numbers, and those trailing numbers will no longer be interpreted as a semantic version.
> [Version] Only strip leading "v" or "version-" when parsing SemVer

- Source/CarthageKit/Cartfile.swift
Noticed some spaced mixed below a tab in `Cartfile.swift`.
> Style: Convert errant spaces to tab.

- Source/carthage/Archive.swift
It took a bit of research to find out that you need to use «carthage
build --no-skip-current» first. I think this error message is a bit more helpful.
> Clarify how to build before creating archive.

- Source/CarthageKit/GitHub.swift
JSON deserialization of a GitHub release fails when the name field is null. Currently, the implementation of `GitHubRelease` only accepts empty strings as values of name. This ammends releases to allow nil strings as well.
> Allow github releases with null names

- Source/carthage/Build.swift
Resolves https://github.com/Carthage/Carthage/pull/552#discussion_r32374292.
> Remove redundant watchOS definition from BuildPlatform.acceptedStrings

- Source/CarthageKit/Xcode.swift
- Source/carthage/Build.swift
This is the same as ReactiveCocoa/ReactiveCocoa#2049.
> Remove Equatable implementations for enums without associated values

- .travis.yml
- Makefile
Now `make package` will archive `CarthageKit.framework` into the working directory automatically.
> Upload CarthageKit.framework to releases with Travis

- Source/CarthageKit/GitHub.swift
This can be important, as I’ve found out. Specifically, our CI depends on having the environment set. Without it, our credentials can't be looked up, leading to anonymous API usage which can be rate limited.
> Inherit the environment of the parent

- Source/carthage/CopyFrameworks.swift
> Remove explicit unwrap of optional when looking for framework source

- Source/CarthageKit/Xcode.swift
- Source/CarthageKitTests/XcodeSpec.swift
Fixes #507.
This is basically working at this point. I'm open to any feedback you have on the approach I've taken. Currently I just look for `*.framework.dSYM` and copy that into Carthage's build directory alongside the framework.
The main thing missing here is creating a universal dSYM for both iOS platforms. I'm not entirely sure whether this is necessary, as you usually won't need to symbolicate crash reports for simulator builds—but maybe there's a use case I'm not thinking of?
This could probably do with a test that the iOS dSYM includes the arm architectures rather than simulator.
> Copy dSYM files alongside built frameworks

- Source/CarthageKit/Xcode.swift
The mapped value is discarded anyway.
> Remove useless map() phase

- CONTRIBUTING.md
Added instructions on how to install your development build when testing local changes to your Carthage clone. This was the upshot of the conversation on Issue #581.
> Added instructions to CONTRIBUTING.md

- Source/CarthageKit/Xcode.swift
Resolves #504.
~~This currently sets the flag for all `xcodebuild` tasks other than `xcodebuild build`.~~
> Set ONLY_ACTIVE_ARCH=NO when building

- Source/CarthageKit/Xcode.swift
- Source/CarthageKitTests/XcodeSpec.swift
Fixes https://github.com/Carthage/Carthage/pull/632#issuecomment-124813933.
> Allow dependencies which have no projects, not to error out with `.NoSharedFrameworkSchemes`

- Source/CarthageKit/Xcode.swift
Takes over @neonichu's work in #621.
> Fix error descriptions of some `.ParseError`

- Source/CarthageKit/Project.swift
> Use the tag name instead of its SHA for Cartfile.resolved when pinned to an exact tag

- Source/CarthageKit/Xcode.swift
We were filtering out schemes that don’t actually sit in the given
project. That works great when you’re deciding what to build, but not
when you’re deciding where to build it from.
We should be building from the workspace (if there is one) to correctly pick up dependencies.
Move the filtering to happen only where we decide which schemes to
build.
> Build schemes from workspaces, not projects

- Source/CarthageKit/Xcode.swift
This fixes problems when the project deployment version is lower than the target's deployment version. In that case `xcodebuild` chooses the first destination on the list, which is iPad 2 (7.1) as of Xcode 6.4. Some projects that have targets for both a static library and dynamic framework have such a configuration (for example [HTMLReader](https://github.com/nolanw/HTMLReader)), as they support a lower deployment version for the static library than the framework.
The destination name is hardcoded to iPhone 6 because I'm currently not aware of a way to list all valid destinations.
> Add -destination flag to build arguments when building for the simulator

- Source/CarthageKit/Project.swift
- Source/carthage/Extensions.swift
> Make a GitHub API request failure a warning and non-fatal

- Source/CarthageKit/Git.swift
`--recursive` option for `submodule sync` is introduced in [git 1.8.1](https://github.com/git/git/blob/5d417842efeafb6e109db7574196901c4e95d273/Documentation/RelNotes/1.8.1.txt#L98) (but that is documented in [2.0.2](https://github.com/git/git/blob/ebc5da3208824e25a89672a3b91bd13629b215fe/Documentation/RelNotes/2.0.2.txt#L4-L5)).
Fixes #184.
> Run `git submodule sync` recursively

- Source/CarthageKit/Errors.swift
- Source/CarthageKit/Project.swift
- Source/CarthageKit/Xcode.swift
- Source/carthage/Build.swift
- Source/carthage/Extensions.swift
This improves console output for that error, and make it possible to continue building other dependencies.
This is based on the discussion in #675. /cc @yasuoza
> Warn .NoSharedFrameworkSchemes error, not to error out

- Source/CarthageKit/Errors.swift
- Source/CarthageKit/Project.swift
- Source/CarthageKit/Xcode.swift
- Source/CarthageKitTests/XcodeSpec.swift
- Source/carthage/CopyFrameworks.swift
Roughly behaves as follows:
- For each framework included in the archive:
- Find its architecture UUIDs with `dwarfdump --uuid`
- Iterate through the contents of the archive and locate any items with the `com.apple.xcode.dsym` type identifier
- For each dSYM, find its architecture UUIDs with `dwarfdump --uuid`
- If a dSYM is located in the archive that matches the UUIDs to those in a downloaded framework, copy it to the same destination as that framework
Fixes #671
> Copy dSYMs from downloaded archives to build folders

- README.md
From the conversation in the Carthage Slack channel, because embedding frameworks is handled by `carthage copy-frameworks`, using “Linked Frameworks and Libraries” section is appropriate for iOS application targets. I'm sorry for that confusion. :bow: 
See #681.
> Revert 42ccb03

- Source/carthage/Extensions.swift
I'm hoping that this will make it a little clearer that it's downloading a pre-built copy. I wanted to include the work _binary_ since the flag is `--use-binaries`.
> Use a more descriptive description for downloads

- Source/CarthageKit/Project.swift
- Source/carthage/Checkout.swift
Fixes #419:
> 1. Disable binary downloads by default when using submodules
I'm not sure if f448fc5 is needed and d4fbb78 is sufficient.
> Disable binary downloads when using submodules

- Source/CarthageKit/Resolver.swift
Should fix #415.
The results in `Cartfile.resolved` with `github "Carthage/Carthage" "master"`:
```
// before (Carthage 0.8)
github "robrix/Box" "1.2.2"
github "jdhealy/PrettyColors" "v2.0.0"
github "thoughtbot/Runes" "v2.0.0"
github "Carthage/ReactiveTask" "0.7-beta.3"
github "antitypical/Result" "0.4.4"
github "Carthage/Commandant" "0.6.1"
github "ReactiveCocoa/ReactiveCocoa" "v3.0-RC.1"
github "thoughtbot/Argo" "v1.0.4"
github "Carthage/Carthage" "aed38106616578f6269b5d72f4d2dbad58beceab"
// after
github "robrix/Box" "1.2.2"
github "jdhealy/PrettyColors" "v2.0.0"
github "thoughtbot/Runes" "v2.0.0"
github "antitypical/Result" "0.4.4"
github "Carthage/Commandant" "0.6.1"
github "ReactiveCocoa/ReactiveCocoa" "v3.0-RC.1"
github "Carthage/ReactiveTask" "0.7-beta.3"
github "thoughtbot/Argo" …
```
> Fix wrong build order with nested dependencies

- Source/CarthageKit/Xcode.swift
Might fix #591, although I can't reproduce the issue and don't confirm that is fixed at my local machine. :astonished:
> Work around an indeterministic NSFileWriteFileExistsError when downloading binaries

- Source/CarthageKit/Git.swift
This may be a more simple way to achieve this function's goal of removing potential ".git" suffixes.
Hope it helps!
> cleaner implementation of stripGitSuffix function

- Source/CarthageKit/Errors.swift
- Source/CarthageKit/Project.swift
- Source/CarthageKit/Xcode.swift
- Source/CarthageKitTests/XcodeSpec.swift
- Source/carthage/Build.swift
- Source/carthage/Update.swift
Resolves #592.
This allows `BuildOptions` to take comma-separated values for the `--platform` option as follows: `--platform ios,mac`
This is a breaking change to CarthageKit's public APIs.
> Accept multiple platforms in BuildOptions

- Source/CarthageKit/Project.swift
Should fix #706 and #711.
The [manpage of `rename()`](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man2/rename.2.html) says:
> Both old and new must be of the same type (that is, both must be either directories or non-directories) and __must reside on the same file system__.
On the other hand, the documentation of `NSFileManager.moveItemAtURL()` says:
> If the source and destination of the move operation are not on the same volume, this method copies the item first and then removes it from its current location.
> Use NSFileManager.moveItemAtURL() as a fallback of rename() system call when EXDEV error occurred

- Source/CarthageKit/Git.swift
- Source/CarthageKit/GitHub.swift
- Source/CarthageKitTests/CartfileSpec.swift
- Source/CarthageKitTests/ResolverSpec.swift
- Source/CarthageKitTests/TestCartfile
Addresses https://github.com/Carthage/Carthage/issues/745#issuecomment-139491947.
The following is the current output before this PR with the input `github "https://github.com/danielgindi/ios-charts.git"` or `github "danielgindi/ios-charts.git"`:
```sh
*** Cloning ios-charts.git
A shell task failed with exit code 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled
```
> Strip .git suffix from GitHub repository name as GitURL does

- Source/CarthageKit/Git.swift
After upgrading to 0.9, I started getting crashes like:
> *** Cloning SwiftCheck
*** Checking out SwiftCheck at "v0.3.0"
2015-09-13 03:05:31.289 carthage[56929:3098569] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'working directory doesn't exist.'
*** First throw call stack:
(
0   CoreFoundation                      0x00007fff9107d03c __exceptionPreprocess + 172
1   libobjc.A.dylib                     0x00007fff9234176e objc_exception_throw + 43
2   CoreFoundation                      0x00007fff9107ceed +[NSException raise:format:] + 205
3   Foundation                          0x00007fff93eb71d6 -[NSConcreteTask launchWithDictionary:] + 582
4   ReactiveTask                        0x0000000107769a45 …
> Handle nonexistent directory in `isGitRepository`

- Source/CarthageKit/Errors.swift
- Source/CarthageKit/Project.swift
- Source/CarthageKit/Xcode.swift
Currently platform determination of precompiled binaries depends on the architecture of the framework. However, with the addition of watchOS frameworks, this behavior is now incorrect, as both watchOS and iOS frameworks share the `arm` prefix on their architectures, resulting in the behavior documented in #757. To remedy this, instead of relying on architecture, we instead perform the following:
- For each downloaded framework, locate the included Info.plist (location differs in Mac OSX vs. iOS frameworks)
- Within the Info.plist, search for the DTSDKName key
- Strip the version numbers from the SDK name, e.g. `macosx10.10` → `macosx`
- Move the framework to the folder that matches the platform name, as before
Fixes #757
I've tested this with RAC 3.0 and the 4.0 alpha. Let me know if …
> Fix precompiled framework platform determination

- Source/CarthageKitTests/XcodeSpec.swift
Those specs test `iOSSigningIdentitiesConfigured()` helper function, not the CarthageKit's APIs.
> Remove useless specs from XcodeSpec.swift

- Source/CarthageKit/Project.swift
If not falls back to '~/.carthage' folder. Also the fall back
URL is constructed using the $HOME enviromental variable if
available otherwise by expanding the tilde.
This commit also fixes an issue with Homebrew testing carthage
in a sandboxed mode. For more info about the Homebrew issue check
https://github.com/Homebrew/homebrew/pull/43884
> Checks if cache dependency folder is writable.

- Source/CarthageKit/Project.swift
- Source/CarthageKit/Xcode.swift
- Source/CarthageKitTests/XcodeSpec.swift
- Source/carthage/Build.swift
Fixes #797. This changes the public `SDKFilterCallback` signature to return `Result<[SDK], CarthageError>`.
The output using Xcode 7.0 with this is as follows:
```sh
$ carthage build
*** xcodebuild output can be found in /var/folders/03/cr990fvs5g73tt4gq52h3j7r0000gn/T/carthage-xcodebuild.aQ45sV.log
*** Building scheme "Nimble-OSX" in Nimble.xcodeproj
*** Building scheme "Nimble-iOS" in Nimble.xcodeproj
A shell task failed with exit code 64:
xcodebuild: error: SDK "appletvsimulator" cannot be located.
```
or 
```sh
$ carthage build --platform ios
*** xcodebuild output can be found in /var/folders/03/cr990fvs5g73tt4gq52h3j7r0000gn/T/carthage-xcodebuild.a4PqQN.log
*** Building scheme "Nimble-iOS" in Nimble.xcodeproj
```
The above correctly ignores tvOS platform which is included in the …
> Avoid crashing with unknown SDKs for universal framework targets

- Source/CarthageKit/Git.swift
> Reject a submodule directory which is not initialized in isGitRepository()

- Source/carthage/CopyFrameworks.swift
Xcode 7.0.1 set environments on building for watchOS Simulator:
```sh
CODE_SIGNING_ALLOWED=YES
EXPANDED_CODE_SIGN_IDENTITY=""
```
It cause launching `codesign` with empty identity option and error.
Xcode 7.1 beta 2 is same for watchOS Simulator.
But it is not happen for tvOS Simulator.
Is this related to #755?
> Fix "no identity found" on `copy-frameworks` for watchOS Simulator

- README.md
I think this rewording will clarify that `carthage update` itself will build each dependency (and sub-dependencies). Elsewhere in the readme, we use `then` to specify a subsequent action to be performed.
> Revise phrasing in OS X getting started

- Source/CarthageKit/Git.swift
When submodule was already checked out,
`carthage update` stopped with following error:
```
fatal: destination path '…' already exists and is not an empty directory.
```
It was caused in `isGitRepository()`.
The output from `launchGitTask` contained line ending,
so `fileExistsAtPath()` never returned true.
Besides the output pointed relative path of `directoryURL`,
and it was not current directory of `defaultManager()`.
> Fix error on `carthage update`

- Source/CarthageKit/Xcode.swift
- Source/CarthageKitTests/XcodeSpec.swift
Fixes #383.
Xcode doesn't copy `Modules` directory in a framework at all in its “Copy Files Phase”.
> Strip `Modules` directory too in copy-frameworks

- Source/CarthageKit/Cartfile.swift
Thought it might be better to use the swift string version of the enumerateLines method.
> Use native swift String version of enumerateLines

- README.md
This will save people on Xcode 7.x/El Cap some time so they don’t attempt to install via Homebrew, get a build error, search for the issue, and realise that it’s not supported.
> Added note to only use homebrew install on Xcode 6.x

- Source/CarthageKit/Git.swift
`git rev-parse --git-dir` returns not only relative path but also absolute path. When absolute path was returned, it caused "fatal: destination path" error.
```sh
% git rev-parse --git-dir
.git
% cd Carthage/Checkouts/Argo
% git rev-parse --git-dir
/Users/norio/Documents/workspace/github/Carthage/.git/modules/Carthage/Checkouts/Argo
% 
```
> Fix "fatal: destination path … already exists" on checkout

- README.md
- Source/CarthageKit/Project.swift
- Source/CarthageKit/Xcode.swift
- Source/carthage/Archive.swift
- Source/carthage/CopyFrameworks.swift
These files are necessary in order to archive a built product that includes bitcode.
This change makes it copy the bcsymbolmap files to the Carthage/Build/$plat folder,
as well as archiving them with `carthage archive` and installing them from prebuilt
archives.
Note, I have not actually tested the prebuilt archive stuff, as there are no prebuilt
archives with bcsymbolmap files (that I'm aware of) today.
This also changes `carthage copy-frameworks` to also copy the bcsymbolmap files
into the build products folder whenever an archive is done. It has a flag
`--copy-bcsymbolmaps` that can be used to copy them on other builds too if desired.
> Copy bcsymbolmap files when building

- Documentation/BashZshCompletion.md
- README.md
Add documentation about Bash/Zsh completion feature as Pull Request #731.
The update of the documentation is in this separated Pull Request to hide the documentation until a new version of Carthage with PR #731 merged is released. **Please merge this PR after the new release** to avoid confusing users of the current version.
> Add documentation about Bash/Zsh completion (PR #731)

- .travis.yml
That has no effect for GitHub Releases.
http://docs.travis-ci.com/user/deployment/releases/ says:
> Please note that deploying GitHub Releases works only for tags, not for branches.
> Remove deploy:on:all_branches from .travis.yml

- Source/CarthageKit/GitHub.swift
> Uses github access token to clone https URLs for github repos

- Source/CarthageKit/Xcode.swift
- Source/carthage/Build.swift
Fixes #897.
If `AD_HOC_CODE_SIGNING_ALLOWED=NO` and `CODE_SIGN_IDENTITY=-` are both set, an error like `ad hoc code signing not allowed with SDK 'iOS 9.1'` would happen, and `-sdk macosx` does not have the former setting, but other sdks have the setting:
```bash
$ xcodebuild -workspace ReactiveCocoa.xcworkspace/ -scheme ReactiveCocoa-Mac -showBuildSettings | grep CODE_SIGN
CODE_SIGNING_ALLOWED = YES
EXPANDED_CODE_SIGN_IDENTITY = 
EXPANDED_CODE_SIGN_IDENTITY_NAME = 
$ xcodebuild -workspace ReactiveCocoa.xcworkspace/ -scheme ReactiveCocoa-iOS -sdk iphonesimulator -showBuildSettings | grep CODE_SIGN
AD_HOC_CODE_SIGNING_ALLOWED = NO
CODE_SIGNING_ALLOWED = NO
CODE_SIGN_CONTEXT_CLASS = XCiPhoneSimulatorCodeSignContext
EXPANDED_CODE_SIGN_IDENTITY = 
EXPANDED_CODE_SIGN_IDENTITY_NAME = 
$ …
```
> Accept ad hoc code signing

- Source/CarthageKit/Cartfile.swift
- Source/CarthageKit/Version.swift
This would be helpful for something like `OutdatedVersion` in #598.
> Loosen VersionType constraint

- Source/CarthageKit/Git.swift
Fixes #817. Fixes #901.
This enables to run `carthage update --use-submodules` (or `bootstrap`) on repositories that are using submodules and the submodules are not initialized or updated yet.
#819 didn't fix the issue. :bow:
> Check if a submodule is initialized/updated when adding it to a repository

- Source/CarthageKit/Xcode.swift
This seems to be required for Xcode 7.2.
https://github.com/Carthage/Carthage/issues/790#issuecomment-159349939 should be the case.
> Specify destination for simulator builds

- README.md
travis can't build with the default xcode_sdk (iphoneos) so force him to use a simulator one.
iphonesimulator9.1 should be present as long as the osx_image is xcode7.1
> Adds xcode_sdk: to the example travis

- Source/CarthageKit/Xcode.swift
Should fix #824.
The order of SDK list which comes form `xcodebuild -showBuildSettings | grep SUPPORTED_PLATFORMS` are different depending on the platform.
- iOS: `iphonesimulator iphoneos`
- watchOS: `watchsimulator watchos`
- tvOS: `appletvos appletvsimulator`
In tvOS case, the simulator build had been the base framework when merging with the device build. Thus, `CFBundleSupportedPlatforms` would be `AppleTVSimulator` and `DTPlatformName` would be `appletvsimulator` in the resulting Info.plist.
This fix ensures that the device build should be the base one when merging the two frameworks.
> Fix merge order of frameworks to ensure that the device build should be the base (destination) one

- Source/carthage/Build.swift
> Allow multiple platform list to contain spaces

- Source/CarthageKit/GitHub.swift
- Source/carthage/Archive.swift
- Source/carthage/Build.swift
- Source/carthage/Checkout.swift
- Source/carthage/Fetch.swift
- Source/carthage/Formatting.swift
- Source/carthage/Update.swift
That will be removed in Swift 3.0, so let's avoid to use it.
> Avoid curried function syntax

- Source/carthage/Update.swift
Took me some time to find out where the platform parameters are documented (only under help build). 
I hope this helps other users.
Maybe `--platform` should also be explained in the Readme.
> listing possible platform parameters in help for the update command

- Source/carthage/Build.swift
- Source/carthage/Checkout.swift
:warning: **THIS IS A BREAKING CHANGE** :warning: 
As discussed in https://github.com/Carthage/Carthage/pull/972#issuecomment-162650937.
That option is now named as `--project-directory`.
> Change the positional argument of `directoryPath` to a named argument

- Carthage.xcodeproj/project.pbxproj
- Source/CarthageKit/Cartfile.swift
- Source/CarthageKit/Project.swift
- Source/CarthageKit/Resolver.swift
- Source/CarthageKitTests/ResolverSpec.swift
- Source/CarthageKitTests/TestResolvedCartfile.resolved
~~The build order is not preserved in `Cartfile.resolved` now.~~
Trying to fix #717 based on the discussion: https://github.com/Carthage/Carthage/issues/717#issuecomment-135501479
> Determine the build order when building the dependencies in Cartfile.resolved

- README.md
Warn about Apple's recommendation that Swift frameworks should be built from source on each machine they're used, suggest some work-arounds.
> Add "Known Issues" section

- README.md
This is what I'm doing when installing library via carthage to tvOS apps.
I'm not sure tvOS has apple submission bug, but seems like Xcode cannot resolve dependencies correctly unless you set `carthage copy-framework` Run Script Phase.
> Add Instruction for tvOS

- Source/CarthageKit/Git.swift
This change clarifies the error message to the dreaded "expected submodule commit SHA in ls-tree output:" error such that you learn what kind of a command gave output that could not be parsed. 
Before this modification there can be a lot of guesswork involved in resolving this error especially if you run `carthage update` on a new project with an existing "legacy" .gitmodules file: I for instance encountered this error with a project with a huge set of existing submodules that I began migrating over to Carthage based dependencies (there were a few weird old submodule dependencies whose brokenness would not be picked up as a build error because they would not result in build errors).
> Clarifies the error message to the 'expected submodule commit SHA in ls-tree output'

- Source/CarthageKit/Xcode.swift
Some types of project changes require a clean to take effect. Typically
this means any change that causes the built product to no longer include
a file/directory it used to include. When building on top of an existing
built product, the old product isn't deleted without cleaning, which
means the resulting built product will still contain the obsolete
file/directory.
If Carthage ever switches to passing a custom derived data path then it
can stop explicitly cleaning (because deleting the derived data
accomplishes the same thing).
> Always clean before building

- Carthage.xcodeproj/project.pbxproj
- Source/CarthageKit/Git.swift
- Source/CarthageKitTests/GitSpec.swift
Fixes #1012. This does not implement the request:
> I think such URLs should have either current logged-in username or "git" by default.
but you can clone or fetch the repo if you have the following entry in your `~/.ssh/config`:
```
Host github.com
User git
```
/cc @inamiy
> Fix parsing scp syntax in GitURL

- Source/CarthageKit/Git.swift
- Source/CarthageKit/Xcode.swift
Correctly ignore submodules inside `--no-use-submodules` checkouts.
Should/might fix #1029.
> Fix picking up submodules in locateProjectsInDirectory()

- Source/CarthageKit/Xcode.swift
- Source/carthage/Archive.swift
This would be useful for some libraries, for example, which have a Objective-C framework and the corresponding Swift one (e.g. https://github.com/CocoaLumberjack/CocoaLumberjack).
```bash
carthage archive CocoaLumberjack CocoaLumberjackSwift
```
> Support multiple frameworks in `archive` command

- Source/CarthageKit/Git.swift
`--prune` option of `man git-fetch` says:
> Tags are not subject to pruning if they are fetched only because of the default tag auto-following or due to a --tags option. However, if tags are fetched due to an explicit refspec (either on the command line or in the remote configuration, for example if the remote was cloned with the --mirror option), then they are also subject to pruning.
Fixes #1027.
> Prune git tags on fetch

- Cartfile.private
- Cartfile.resolved
https://github.com/Quick/Nimble/releases/tag/v3.1.0
> Update Nimble to v3.1.0

- Source/CarthageKit/Errors.swift
- Source/CarthageKit/Xcode.swift
On my old and very slow Mac 'carthage update' fails with a Cartfile that has RxSwift among its dependencies because 'xcodebuild -list' times out, increasing the interval to 60 enables it to continue building.
The error message 
```
Failed to discover shared schemes in project Rx.xcworkspace—either the project does not have any shared schemes, or xcodebuild never returned
```
was also a bit confusing to me, I think the proposed message tweak saying that 'xcodebuild timed out' is more clear about what has happened.
> Increase xcodebuild list timeout

- Source/CarthageKit/Project.swift
Previously the permissions were incorrectly specified as 755 in decimal notation, which resulted in a permissions value of 1363 when converted to octal.
Fixes #842.
~~Weirdly, it appears this also fixes #1072!~~
> Use octal notation when specifying permissions for the Caches directory

- README.md
In this case, "Box," would be treated as a framework name.
c.f. #1089
> [README] There should not be any comma for `carthage update`

- Source/CarthageKit/Project.swift
- Source/CarthageKit/Resolver.swift
- Source/CarthageKitTests/ResolverSpec.swift
Fixes #1080 as an alternative to #1086. I’m not sure if it addresses #765.
I think this a simpler approach to determining build order, and it sidesteps #1080. It’s not straightforward to test, but I did manually test it with some projects and things look good.
/cc @ikesyo
> Don't use Resolver to determine build order

- Source/CarthageKit/Project.swift
@kballard [pointed out](https://github.com/Carthage/Carthage/pull/1100#commitcomment-15925646) that it’s not the right thing to do in this instance.
> Don't use a localized sort

- Source/CarthageKit/Errors.swift
- Source/CarthageKit/Project.swift
Use `NSBundle.objectForInfoDictionaryKey`.
As suggested in https://github.com/Carthage/Carthage/issues/1056#issuecomment-179444959.
> Improve the logic to detect the platform for a framework bundle

- Source/CarthageKit/Project.swift
- Source/CarthageKit/Resolver.swift
- Source/CarthageKit/Xcode.swift
This was removed in #998.
The conclusion of SE-00003 is changed to keep `var` bindings in Swift 3: https://github.com/apple/swift-evolution/blob/faff3215518b71965499b5b5be3475e0be850a01/proposals/0003-remove-var-parameters.md
> Restore `var` bindings

- Source/CarthageKit/Errors.swift
- Source/CarthageKit/Xcode.swift
Fixes #940 for the Xcode 7.3 betas (and presumably all future releases).
Tested by running `carthage bootstrap` with Xcode 7.3b3 with this Cartfile:
```
github "MatthewYork/DateTools"
```
> Add a timeout for xcodebuild -showBuildSettings

- Cartfile.resolved
https://github.com/Quick/Quick/releases/tag/v0.9.1
> Update Quick to v0.9.1

- Source/CarthageKit/FrameworkExtensions.swift
- Source/CarthageKit/Project.swift
- Source/CarthageKit/Resolver.swift
As a first step towards #1081, I cleaned up `Resolver`. I found the existing structure hard to read and understand. This should make it easier to alter to prevent unnecessary fetching.
> Cleanup Resolver

- Carthage.xcodeproj/project.pbxproj
- Source/carthage/Version.swift
- script/update-cli-version
Adds a run script command to building the CLI version of carthage that overwrites the `CFBundleShortVersionString` variable in the Info.plist file be equal to the output of `git describe --tags`.
This means that `carthage version` will output something like `0.13-12-g4859c8c` when we're not on a release tag. Building on a release tag will work as expected.
This, unfortunately, will thrash the Info.plist file every time carthage is built.
If/when accepted, this'll complete #1060.
> Carthage version should display output of git describe

- Carthage.xcodeproj/project.pbxproj
- Source/CarthageKit/Algorithms.swift
- Source/CarthageKit/Cartfile.swift
- Source/CarthageKit/Errors.swift
- Source/CarthageKit/Project.swift
- Source/CarthageKitTests/AlgorithmsSpec.swift
As of #1100,  the `build` command uses a comparison sort to resolve ordering of dependencies to build. That change resulted in frameworks being built out of order in significantly complex dependency graphs, causing "module not found" errors.
To resolve this, [Kahn's topological sort](https://en.wikipedia.org/wiki/Topological_sorting) is used in place of a comparison sort to ensure that the dependency graph is built in the correct order.
In our project with 43 unique dependencies (including transitive dependencies), this change fixed "module not found" errors when using the build command in the most recent release. Additionally, since this is a generic algorithm, it can be easily tested (assuming there is a reasonable place to put it). It would appear #1100 removed the previous tests …
> Fix dependency resolution when building

- Carthage.xcodeproj/project.pbxproj
- Source/CarthageKit/GitHub.swift
- Source/CarthageKit/Project.swift
- Source/CarthageKitTests/Fakes/FakeURLSession.swift
- Source/CarthageKitTests/GitHubSpec.swift
Also test our calls to the network using a faked-out network interface.
I found a bit of unused code while doing this. `fetchAllPages()` in GitHub.swift is only called twice - recursively in `fetchAllPages()`, and in `releaseForTag()`. According to the github api v3 docs, `GET /repos/:owner/:repo/releases/tags/:tag` (the underlying url in `releaseForTag()`) won't ever page. So, unless I'm mistaken, the logic to recursively fetch additional pages is entirely unnecessary. Removing it, however, is outside the scope of this pull request.
Anyway, this is another pull request meant to clean up the code, improve test coverage, and improve test runtime. It doesn't do the last (the only major improvements to the test runtime will come when I can fake out all calls to xcodebuild), but it certainly …
> [WIP] Inject instances of NSURLSession in GitHub.swift

- Source/CarthageKit/BuildArguments.swift
- Source/CarthageKitTests/BuildArgumentsSpec.swift
Adding a build setting `CARTHAGE` makes it possible for framework projects to detect when they are being built by Carthage, as requested in #1148
> Add `CARTHAGE` build setting to xcodebuild arguments

- .travis.yml
- Makefile
- Source/CarthageIntegration/README.md
- Source/CarthageIntegration/archive.bats
- Source/CarthageIntegration/update.bats
Adds an integration test suite that uses [bats](https://github.com/sstephenson/bats) to test the carthage CLI.
Currently only tests archive, have plans to test others.
If you'd rather not promote Ra, then feel free to suggest some other repo.
> Add an integration test suite

- Source/CarthageKit/Xcode.swift
Symptoms
========
In our project, we use `carthage copy-frameworks` as a `run script` phase in "main" the XCode project, passing as input parameters: `$(SRCROOT)/Carthage/Build/iOS/<famework-name>.framework` with some frameworks that we developed.
In case we want to debug one of the dependent projects within the "main" one,  just drag the dependent project in to the main project and change the parameter to: `$(BUILT_PRODUCTS_DIR)/<framework-name>.framework`
This causes the script to pick up the locally built copy of the framework with minimal effort (no need to use submodules) and we can then debug the locally built version of the framework.
This behaviour was broken when switching to carthage version 0.11. It was working fine in 0.10.
When setting the input parameter as …
> Avoid deleting resource when trying to copy to and from the same path

- Carthage.xcodeproj/xcshareddata/xcschemes/carthage.xcscheme
Check out the carthage project and open it in Xcode 7.2.1.
When trying to run carthage from XCode (`Cmd+R`), the process fails with the output (in the Xcode console):
`Unrecognized arguments: -DnouvMtSdbiNmcResg`
The `Run` section of the carthage schema in XCode has no such command line argument, in fact it only has `update`.
By setting a breakpoint in Commandant and printing out the actual command line arguments, it turns out that there are two extra unexpected arguments passed when running carthage from XCode 7.2.1:
- `-NSDocumentRevisionsDebugMode`
- `YES`
Looking at the string `-DnouvMtSdbiNmcRes`, it turns out it's just an anagram of `-NSDocumentRevisionsDebugMode` with duplicate letters removed. The initial `-` makes Commandant think it's a cluster of flags (as in `tar -xvf`), so it …
> Fix `Unrecognized arguments: -DnouvMtSdbiNmcResg` when running from XCode

- Source/CarthageKit/GitHub.swift
As reported in #1172 , `carthage` is treating
`github "Owner/Repo"` and
`github "owner/repo"`
as two different dependencies causing duplicated entries in `Cartfile.resolved`.
Fixed it by adding case-insensitive hash generation in `GitHubRepository`
> Fixes #1172, duplicate dependency entries

- Source/CarthageKit/Git.swift
- Source/CarthageKit/Project.swift
Fixes #1166.
`versionsForProject` returns an error if there are no tags as of #1127.
> Resolve tags directly

- README.md
- iOS application targets now have the "Linked Frameworks and Libraries" section in their “General” settings
- Only unit test targets are missing the "Linked Frameworks and Libraries" section
> [README] Update "Adding frameworks to unit tests or a framework" section

- Source/CarthageKit/Resolver.swift
- Source/CarthageKit/Xcode.swift
As of #1197, the deployment target is 10.10 now. So we should replace the deprecated `QueueScheduler.init(queue:name:)` with `QueueScheduler.init(qos:name:)`.
> Use QueueScheduler.init(qos:name:)

- Source/CarthageKit/Algorithms.swift
- Source/CarthageKit/Project.swift
- Source/CarthageKitTests/AlgorithmsSpec.swift
Currently, deep transitive dependencies are not built first before a dependency when it is specified to the build command. This occurs when you specify a specific set of dependencies to the "build" command.
An example would be `carthage build A`, where `A` depends on `B` depends on `C`. I have observed that `C` is not always built before `B`.
> Fix building with transitive dependencies

- Source/carthage/main.swift
Per @schwa's request (#1148) and @kballard's idea this adds a $CARTHAGE environment variable which is set to the path of the currently running carthage executable so that the build can:
- know it is running under carthage
- call copy-frameworks, etc with the same version of carthage if desired.
> #1148 - Add CARTHAGE_PATH env var with executable path

- Source/carthage/main.swift
- Use `NSBundle.executablePath` over `executableURL?.path`
- Pass `carthagePath` directly to `setenv`
- Add a missing space after comma
> Minor fixes for #1154

- Source/CarthageKit/Project.swift
> Don't error if a GitHub Release doesn't exist

- Source/carthage/CopyFrameworks.swift
I have a (dynamic)framework that wraps static libs, but these binaries are not build for the simulator. It turns out that lipo throws an error if the result is an empty binary, in the copy-frameworks command. In this pr i added a function `shouldIgnoreFramework` that checks if the framework does support any of the valid architectures and if that returns false the i print a warning and the framework will be ignored.
> [copy-frameworks] Ignore frameworks that do not support the current build architecture

- README.md
TravisCI updated their VMs and `brew install carthage` now fails with error: "already installed".
I changed this to `brew outdated carthage || brew upgrade carthage`, so it will try to update only if carthage is outdated and no error will be produced.
> Fix CI steps in readme

- Source/CarthageKit/Xcode.swift
This is an attempt to get Carthage working for test frameworks like Quick and Nimble on the tvOS platform.
I'm new to ReactiveCocoa so I welcome any advice or suggestions on better ways to hook in this logic. Also, I'm not sure how to set up tests for this change as it looks like the current build tests in `XcodeSpec` all actually trigger real builds. Perhaps once I add `ENABLE_BITCODE=NO` to Quick and Nimble their projects could be used to test this.
Resolves #1268
> Skip building for device SDKs on platforms that require bitcode when bitcode is disabled

- Source/carthage/Build.swift
With regard to https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2831.
> Remove SignalProducer.buffer usage

- Source/CarthageKit/Errors.swift
- Source/carthage/Bootstrap.swift
I'm not very sure if this fits your house style and whether I've missed something obvious, but here's an attempted fix to #1292. 
Also some shortcuts taken to force unwrap where some suitable errors should be thrown instead (on failing to read a string from Cartfile.resolved or to parse it into a ResolvedCartfile), wasn't sure what the intended style for such error cases is.
> Fix to https://github.com/Carthage/Carthage/issues/1292

- README.md
This path must be present for Carthage to load frameworks in unit test targets, but may not be present in older projects.
I discovered this while using Carthage to add libraries to the unit test target here:
https://github.com/wikimedia/wikipedia-ios/pull/695
> Update ReadMe to add note about @loader_path/Frameworks

- Source/CarthageKit/BuildArguments.swift
- Source/CarthageKit/Project.swift
- Source/CarthageKit/Xcode.swift
- Source/CarthageKitTests/BuildArgumentsSpec.swift
- Source/carthage/Archive.swift
- Source/carthage/Build.swift
- Source/carthage/Update.swift
Adds the ability to specify a custom Swift toolchain via a `--toolchain` option on the `build`, `update`, and `archive` commands.
E.g.: `carthage build --toolchain org.swift.3020160509a`
**Todo**
**Resolves issue** #1039
> Add `--toolchain` option

- Source/carthage/Archive.swift
When running the archive command on projects with test targets that have "Run" enabled in the build scheme, as below:
This error is shown:
Could not find any copies of SnapKit OSX Tests.xctest, SnapKit iOS Tests.xctest, SnapKit.framework. Make sure you're in the project’s root and that the frameworks have already been built using 'carthage build --no-skip-current'.
Apart from SnapKit this issue is happening on PromiseKit as well.
This fix adds a filter to filter out anything that is not a framework.
> Fixes issue with archive command trying to include xctest files

- README.md
Change from:
```
/usr/local/bin/carthage build --platform "$PLATFORM_NAME" "$SRCROOT"
``` 
To:
```
/usr/local/bin/carthage build --platform "$PLATFORM_NAME" --project-directory "$SRCROOT"
```
The Run Script won't function without `--project-directory`.
> Clarify Run Script build phase

- Source/CarthageKit/Errors.swift
- Source/carthage/Update.swift
same as #1292 on `update` command.
> Fix carthage update silently fails when attempted for a package which does not yet exist in Cartfile

- Source/CarthageKit/Xcode.swift
#1377 stoped copying the `Headers` directory, but didn't include the `PrivateHeaders` directory, which is still being copied.
Ref #1377 #1337
> Strip PrivateHeaders directory from copied frameworks

- Source/carthage/Build.swift
The possible SDK values we pass to `xcodebuild -sdk` are not `tvos` nor `tvsimulator`.
Maybe we should remove the `"tvsimulator": .tvOS` case?
> [carthage] Accept `appletv(os|simulator)` for `--platform` option

- README.md
> ReadMe: added solution to the (not well-documented) situation where Xcode won't compile because the library binary(s) used a different version of the compiler.
Hi there --
After hours of trying to diagnose a compiler error that prevented dependencies from building in multiple Xcode projects, then spending quite a bit of time investigating whether having two versions of Xcode on the machine (7.3.1 and 8b2) could have been the cause (e.g., by munging the command line tools, which wasn’t the case) … I finally found a StackOverflow solution that fit the situation (http://stackoverflow.com/a/36661798).  [I was about to give up on Carthage altogether when I found this just in time.]
Since Carthage seems to prefer downloading precompiled binaries which may or may not compile in a given user’s …
> Added troubleshooting solution to ReadMe file (for "Module file was created by an older/newer version of the compiler” compile error).

- Source/carthage/main.swift
Fixes [#1438](https://github.com/Carthage/Carthage/issues/1438)
The change makes `printf` flush it's buffer for every new line. This is standard behaviour when it runs in TTY, but when output is file or pipe, then the buffer mode changes to block buffering.
The solution tested and it works, but probably, calling `setlinebuf` in the beginning of `main.swift` is not the best idea. If you point out the right place for it, I can easily fix that.
Looking forward for any feedback.
> Configured stdout to always flush the buffer at the end of each line

- Source/CarthageKit/Git.swift
- Source/CarthageKit/Project.swift
Fixes #1324.
AFAICT this only happens when the repository doesn’t exist (or when you don’t have access to it, in which case it doesn’t appear to exist).
> Fix crash when repository not found

- Source/CarthageKit/Xcode.swift
This is to work around an xcodebuild bug (rdar://27052195; introduced with xcode 8) that causes a complete hang if the target contains a core data model. Further discussion here:
https://forums.developer.apple.com/thread/50372
Credits for workaround to IngmarStein in dev forums
> Added "clean" to xcodebuild -showBuildSettings to work around rdar://27052195

- Source/CarthageKit/Git.swift
- Source/CarthageKit/Project.swift
- Source/CarthageKitTests/ProjectSpec.swift
I don't believe there's an issue that tracks this. This is my attempt to reduce the amount of times we fetch a dependency.
This started occurring with the fix for #1202 (which was needed because I caused a regression for branches in my previous fetch optimization =/ )
What this change does is write out a custom config to the cache repo that specifies the last time carthage itself ran a fetch. Then we skip fetching if it occurred within the last minute. This avoids adding any state to Carthage in case of long running CarthageKit usage, but still optimizes the majority of cases where we're just looping through the dependencies and fetching them all during resolution.
The other approach I thought of that could be more accurate, but would require a lot more plumbing through the system, would …
> Redundant update fetches

- Source/CarthageKit/FrameworkExtensions.swift
- Source/CarthageKitTests/FrameworkExtensionsSpec.swift
This should be a simpler solution for the issue described in #1431.
https://developer.apple.com/reference/foundation/nsurl/1414302-standardizingpath
> - Expand an initial tilde expression using stringByExpandingTildeInPath.
> - Reduce empty components and references to the current directory (that is, the sequences “//” and “/./”) to single path separators.
> - In absolute paths only, resolve references to the parent directory (that is, the component “..”) to the real parent directory if possible using stringByResolvingSymlinksInPath, which consults the file system to resolve each potential symbolic link.
>     In relative paths, because symbolic links can’t be resolved, references to the parent directory are left in place.
> - **Remove an initial component of “/private” from the path if …
> Use `NSURL.URLByStandardizingPath` in `NSURL.hasSubdirectory` extension

- Source/CarthageKit/Git.swift
* `carthage version`: `0.16.2`
* `xcodebuild -version`: 
```
Xcode 7.3.1
Build version 7D1014
```
* Are you using `--no-build`? *No*
* Are you using `--no-use-binaries`? *Yes*
* Are you using `--use-submodules`? *No*
**Cartfile**
```
github "Alamofire/Alamofire" ~> 3.4
```
**Carthage Output**
```
*** Fetching Alamofire
*** Checking out Alamofire at "1.2.0         2.0.0-beta.3  3.1.0         3.3.1"
*** Fetching Alamofire
A shell task (/usr/bin/env git checkout --quiet --force 1.2.0         2.0.0-beta.3  3.1.0         3.3.1) failed with exit code 1:
error: pathspec '1.2.0         2.0.0-beta.3  3.1.0         3.3.1' did not match any file(s) known to git.
```
---
This is happening because the command intended to list all of the tags doesn't
take into account the possibility of the end user's …
> Fix how tags are listed.

- Source/carthage/Build.swift
- Source/carthage/Formatting.swift
When executing `carthage help`, it outputs four kinds of quotation.
It would be nice to use only apostrophe (\u0027) for this.
| Before | After |
| :---: | :---: |
| ![screen shot 2016-09-14 at 1 28 06 pm](https://cloud.githubusercontent.com/assets/932290/18500054/1f7ecd12-7a7f-11e6-80ca-2e177026004b.png) | ![screen shot 2016-09-14 at 1 27 05 pm](https://cloud.githubusercontent.com/assets/932290/18500052/1eb89188-7a7f-11e6-8582-0ea910863dd7.png) |
| Full output (carthage help build) | Full output (carthage help build) |
| ![screen shot 2016-09-14 at 12 54 42 pm](https://cloud.githubusercontent.com/assets/932290/18499981/a5e2f41a-7a7e-11e6-9e3c-61b164ab7baf.png) | ![screen shot 2016-09-14 at 12 47 16 pm](https://cloud.githubusercontent.com/assets/932290/18499986/abc51886-7a7e-11e6-9da5-2aff …
> Replace quotation with apostrophe

- Source/carthage/Build.swift
Modify help message about `--platform` option.
I think it should be `macOS`.
Platform `Mac` is still working, but primary value should be `macOS`.
Because shell completions suggest `macOS`.
https://github.com/Carthage/Carthage/pull/1390/files#diff-cedb56bc6f242f0c6891894f472948c9R70
Please review it. 🙏
> Modify help message for platform options

- Source/CarthageKit/Git.swift
I'm trying to figure out why `Carthage` is failing to update `xcconfigs` now:
> Failed to check out repository into /Users/nachosoto/Library/Caches/org.carthage.CarthageKit/dependencies/xcconfigs: No object named "master" exists
I cleared `Users/nachosoto/Library/Caches/org.carthage.CarthageKit` but still no luck. Note that I had already correctly fetched this, so I don't know why this is suddenly broken.
Looks like this is similar to #400. I ran `git rev-parse master` from that folder:
> [nachosoto(master)]$ git rev-parse master
> cc451b08e052b6146f5caf66bc1120420c529c7b
But as you can see that's not the problem. This PR should hopefully provide more visibility into the actual underlying issue.
_Note: I'm on version `0.18.1`._
---------------
I just figured out what was wrong: I had the …
> Git: added underlying error when generating CarthageError.RepositoryCheckoutFailed

- .travis.yml
It wasn't creating the correct version number.
Fixes #1528.
> Remove the travis deploy step

- Source/CarthageKit/Xcode.swift
Credits: https://github.com/samsonjs/Carthage/commit/946e202019c9ede36a4ea6cfb57df067dd8cb3ee
Fixes https://github.com/Carthage/Carthage/issues/1310. Please see that issue for details.
Here is a set of examples with failures:
* iOS: https://travis-ci.org/mattt/FormatterKit/jobs/159922844#L774-L777
* macOS: https://travis-ci.org/mattt/FormatterKit/jobs/159922845#L774-L777
* watchOS: https://travis-ci.org/mattt/FormatterKit/jobs/159922846#L774-L777
* tvOS: https://travis-ci.org/mattt/FormatterKit/jobs/159922847#L774-L777
And here I used my fork of Carthage:
* iOS: https://travis-ci.org/mattt/FormatterKit/jobs/165110137
* macOS: https://travis-ci.org/mattt/FormatterKit/jobs/165110138
* watchOS: https://travis-ci.org/mattt/FormatterKit/jobs/165110139
* tvOS: …
> Increasing Xcode timeout from 30 to 60 seconds

- Source/CarthageIntegration/update.bats
The failure is seen here: https://travis-ci.org/Carthage/Carthage/jobs/167228879. That is because Argo v2.3.0 did not specify version constraint for Curry in its `Cartfile.private`. So when running `carthage update` in the checked out repository, the latest Curry v3.0.0 for Swift 3, which can't be built by Xcode 7.3, will be used. ~~Using Argo v3.1.0 should fix the problem.~~
> Fix a failing integration test

- Carthage.xcodeproj/project.pbxproj
- Source/CarthageKit/Errors.swift
- Source/CarthageKit/Scannable.swift
- Source/carthage/BuildVersion.swift
- Source/carthage/main.swift
Verifies if the local version of Carthage is up to date.
It should solve #1181 and #1130 
Credits also to @mdiep for his help!
> Remote Version Validation

- Source/CarthageKit/Xcode.swift
`xcodebuild clean -showBuildSettings` can fail if the scheme doesn't support the clean action, same as issue https://github.com/Carthage/Carthage/issues/1541. This adds a flag to skip unavailable actions instead of failing.
An example with PINRemoteImage:
```shell
$ carthage update
*** Checking out PINRemoteImage at "3.0.0-beta.6"
*** xcodebuild output can be found in /var/folders/4x/k22fcvxj09q33bnxlpc1ngv00000gn/T/carthage-xcodebuild.D68Rup.log
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/zach/code/tmp/CarthageTest/Carthage/Checkouts/PINRemoteImage/Example-Mac/PINRemoteImage.xcworkspace -scheme PINRemoteImage -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean -showBuildSettings) failed with exit code 66:
xcodebuild: error: Scheme …
```
> Adds the -skipUnavailableActions flag when retrieving build settings

- Source/CarthageKit/FrameworkExtensions.swift
- Source/CarthageKit/Git.swift
- Source/CarthageKit/Project.swift
- Source/CarthageKit/Swift3Shims.swift
- Source/CarthageKit/Xcode.swift
- Source/carthage/Build.swift
#1558 
Based on [the file](https://github.com/ReactiveCocoa/ReactiveSwift/blob/bac956ee3e93dcad0b5528009362502ec91257c8/Sources/Deprecations%2BRemovals.swift).
> [swift3-prep] Add `Observer.send(value:)` and `Observer.send(error:)` shims

- Source/CarthageKit/BuildArguments.swift
- Source/CarthageKit/Cartfile.swift
- Source/CarthageKit/Git.swift
- Source/CarthageKit/GitHub.swift
- Source/CarthageKit/Project.swift
- Source/CarthageKit/Xcode.swift
- Source/CarthageKitTests/ArchiveSpec.swift
- Source/CarthageKitTests/XcodeSpec.swift
- Source/carthage/Build.swift
- Source/carthage/CopyFrameworks.swift
- Source/carthage/Formatting.swift
This also adopts https://swift.org/documentation/api-design-guidelines/#follow-case-conventions for some occurrences.
#1558
> [swift3-prep] Rename `URL` to `url` to avoid conflict with `Foundation.URL`

- Carthage.xcodeproj/project.pbxproj
- Source/CarthageKit/Cartfile.swift
- Source/CarthageKit/Errors.swift
- Source/CarthageKit/Project.swift
- Source/CarthageKitTests/CartfileSpec.swift
- Source/CarthageKitTests/DuplicateDependencies/Cartfile
- Source/CarthageKitTests/DuplicateDependenciesCartfile
- Source/CarthageKitTests/ProjectSpec.swift
This is the first step in some cleanup I want to do—changing Cartfiles to have `Set`s of dependencies instead of `Array`s, changing `Resolver` to not know about `Cartfile`s, etc.
> Detect duplicates early

- Source/CarthageKit/Cartfile.swift
- Source/CarthageKit/Project.swift
- Source/CarthageKit/Resolver.swift
- Source/CarthageKitTests/ResolverSpec.swift
This simplifies the code a bit and begins to make testing the resolver easier. (You no longer need to construct a `Cartfile` for testing.)
I hope to extend this in the future and making testing even easier.
> Don't use Cartfiles in Resolver

- Carthage.xcodeproj/project.pbxproj
- Source/CarthageKitTests/EmbeddedFrameworksCartfile
- Source/CarthageKitTests/EmbeddedFrameworksContainerCartfile
- Source/CarthageKitTests/ResolverSpec.swift
- Source/CarthageKitTests/TestCartfileProposedVersion
This makes it _much_ easier IMO to understand what it’s testing and to add new tests. It removes the use of all files (test cartfiles, git repos) in favor of a `DB` struct.
> Rewrite ResolverSpec to contain all its data

- Source/CarthageKit/Availability.swift
- Source/CarthageKit/Resolver.swift
- Source/CarthageKit/Version.swift
- Source/CarthageKitTests/VersionSpec.swift
Adopts API Design Guidelines.
#1558
> [SemanticVersion] Rename `fromPinnedVersion(_:)` to `from(_:)`

- Source/CarthageKit/Errors.swift
- Source/CarthageKit/Xcode.swift
- Source/carthage/Build.swift
Direct users to the xcodebuild log to help them self-diagnose errors.
Fixes #1626.
```
$ carthage update --no-use-binaries
*** Fetching Result
*** Checking out Result at "1.0.2"
*** xcodebuild output can be found in /var/folders/xj/sydx1wkd0p147x0k_7v667940000gn/T/carthage-xcodebuild.yIaqhL.log
*** Building scheme "Result-Mac" in Result.xcodeproj
** CLEAN FAILED **
The following build commands failed:
Check dependencies
(1 failure)
** BUILD FAILED **
The following build commands failed:
Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -project /Users/mdiep/Downloads/tmp/Carthage/Checkouts/Result/Result.xcodeproj -scheme Result-Mac -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code …
```
> Don't pass Xcode errors through

- Source/CarthageKit/Algorithms.swift
- Source/CarthageKit/Availability.swift
- Source/CarthageKit/BuildSettings.swift
- Source/CarthageKit/Cartfile.swift
- Source/CarthageKit/Errors.swift
- Source/CarthageKit/FrameworkExtensions.swift
- Source/CarthageKit/Git.swift
- Source/CarthageKit/GitHub.swift
- Source/CarthageKit/ProducerQueue.swift
- Source/CarthageKit/Project.swift
- Source/CarthageKit/ProjectLocator.swift
- Source/CarthageKit/Resolver.swift
- Source/CarthageKit/SDK.swift
- Source/CarthageKit/Version.swift
- Source/CarthageKit/Xcode.swift
- Source/carthage/Archive.swift
- Source/carthage/Bootstrap.swift
- Source/carthage/Build.swift
- Source/carthage/Checkout.swift
- Source/carthage/CopyFrameworks.swift
- Source/carthage/Environment.swift
- Source/carthage/Extensions.swift
- Source/carthage/Fetch.swift
- Source/carthage/Formatting.swift
- Source/carthage/Outdated.swift
- Source/carthage/Update.swift
- Source/carthage/Version.swift
#1558 
We would/should revisit following API Design Guidelines once we have done Swift 3 migration.
> [swift3-prep] Make first parameters unnamed explicitly

- Source/CarthageKit/GitHub.swift
By making this a `URL`, `absoluteString` is no longer optional.
Output was:
> *** Skipped building libextobjc due to the error:
> Dependency "libextobjc" has no shared framework schemes for any of the platforms: iOS
> 
> If you believe this to be an error, please file an issue with the maintainers at Optional("https://github.com/jspahrsummers/libextobjc/issues/new")
> 
Now:
> *** Skipped building libextobjc due to the error:
> Dependency "libextobjc" has no shared framework schemes for any of the platforms: iOS
> 
> If you believe this to be an error, please file an issue with the maintainers at https://github.com/jspahrsummers/libextobjc/issues/new
> Fix printing of newIssueURL

- Source/carthage/Build.swift
This fixes an issue I found, caused by the changes for Carthage/Carthage#1718
1718 filtered the output when !verbose, unfortunately this filtered it out from writing to the log file either, so when in non-verbose mode, you get no xcode output at all.
This instead just routes errors -> stdout when not verbose, thus sending all messages to the log file.
> Don't filter output so it still makes it to the log file

- Makefile
- Source/carthage/Distribution.plist
Fixes #1701 
If you check this out and run `Carthage.pkg` you can see there's a different disk selection UI. We _could_ restrict installation to the local system volume, but this mechanism already limits installation to Volumes containing macOS.
> Restrict installation to volumes with macOS

- README.md
Turns out `bin/sh` does not work, and will make you tear your hair out for 15 minutes until you notice the missing leading slash. This readme change will hopefully spare some people their sanity 🙂
> Readme: Added leading slash for shell example

- README.md
Choosing the easy route from #1785 for starters.
> Update README for cache and submodule incompatibility.

- Source/CarthageKit/Archive.swift
- Source/CarthageKit/Project.swift
- Source/CarthageKitTests/ArchiveSpec.swift
Some organisations provide binary releases in .tar.gz archives rather than zips. With support for extracting these, it becomes easier for them or a third-party to provide the JSON files for binaries. 
This could be expanded to support BZIP etc.
> Add support for .tar.gz binary archives

- Documentation/VersionFile.md
- Source/CarthageKit/VersionFile.swift
- Source/CarthageKitTests/ProjectSpec.swift
- Source/CarthageKitTests/TestVersionFile
- Source/CarthageKitTests/VersionFileSpec.swift
This PR resolves issue #1807.
Other than previously stated [here](https://github.com/Carthage/Carthage/pull/1489#issuecomment-283006776), I used `/usr/bin/shasum -a 256` instead of `/usr/bin/openssl dgst -sha256`. It returns the hash before the path, so it is easier to parse, in case the path contains spaces.
I also renamed occurances of `md5` to `hash` (instead of `sha256`) in case the hashing function has to be replaced again some time in the future. Since this also included renaming the key in the VersionFile, I don't know if this causes trouble. @BobElDevil said in the issue above, that in case the hash doesn't match anymore, carthage will just rebuild the dependency, but what happens if the key doesn't match? I guess it will also just rebuild the dependencies, because it will fall …
> Change md5 to sha256

- Makefile
- Source/CarthageKit/FrameworkExtensions.swift
This should not be an issue anymore.
> Restore the original implementation of `SignalProducerProtocol.permute(with:)`

- Source/CarthageIntegration/Utilities/TestFramework.bash
- Source/CarthageIntegration/Utilities/git-commit.bash
- Source/CarthageIntegration/checked-in-conflicting-differing-directory.bats
- Source/CarthageIntegration/checked-in-conflicting-differing-symlink.bats
- Source/CarthageIntegration/relink-conflicting-not-checked-in-symlink.bats
- Source/CarthageKit/Git.swift
- Source/CarthageKit/Project.swift
*Hopefully, addresses most of #1794*
`git ls-tree -r` would list checked-in submodules, symlinks, the files inside recursed-through directories, but (problematically) not the directories themselves.
Instead, without recursion and with a trailing path separator, `ls-tree` lists just the directory contents, which is what should have been implemented to begin with.
Remove now unnecessary path shallowness check as the task now outputs only the desired depth.
Major apologies for introducing these errors in #1715.
- More Integration tests
- conflicting in both the cases where 
- [the symlink points to the same directory our symlink would](https://github.com/jdhealy/Carthage/commit/dcfd2444176dd42da3f4877faf95f28e8488d268#diff-469c149f42a15fb39e27c78049674004R68)
- *It does, same write error.*
- …
> Execute `git ls-tree` to list just the directory contents, without recursion

- Source/CarthageKit/Cartfile.swift
- Source/CarthageKit/Project.swift
- Source/CarthageKitTests/CartfileSpec.swift
- Source/CarthageKitTests/ProjectSpec.swift
- Source/carthage/Bootstrap.swift
- Source/carthage/Outdated.swift
- Source/carthage/Update.swift
I’m on a quest to remove `Dependency`. I think it provides little value and takes up a valuable name.
This is the first step: changing the Cartfiles to use `[ProjectIdentifier: <Version>]` instead of `Set<Dependency<Version>>`.
I will follow this up with more PRs to remove `Dependency`. Then I plan to rename `ProjectIdentifier` to `Dependency` to better explain its role (in contrast to `Project` and `ProjectLocator`).
> Use Dictionary instead of Dependency in cartfiles

- Source/carthage/CopyFrameworks.swift
From a quick test on a project with 30 frameworks, this speeds up the copy frameworks step for the device target in our application by nearly 4x on a quad-core machine. Before this change, the copy frameworks step takes ~40s, and after this change it takes ~10s.
> Copy frameworks concurrently (~4x speedup)

- Source/CarthageKit/Git.swift
*Potentially, fixes #1787 — I was seeing very similar crash reports…*
Use `URL(fileURLWithPath:)` for top level output from git.
`URL(string:)` can sometimes return nil in cases where `URL(fileURLWithPath:)` and `FileManager.isReadableFile(atPath:)` both validate the path.
- - -
```swift
Welcome to Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1). Type :help for assistance.
1> import Foundation
2>
3> let url = "/Users/jdhealy/Code/Scratch/Result·Illegal·Hardware·Instruction\n"
url: String = "/Users/jdhealy/Code/Scratch/Result·Illegal·Hardware·Instruction\n"
4>
5> URL(string: url.trimmingCharacters(in: .newlines))
$R0: URL? = nil
6>
7> url.trimmingCharacters(in: .newlines)
$R1: String = "/Users/jdhealy/Code/Scratch/Result·Illegal·Hardware·Instruction"
8>
9> …
```
> Fix crashing URL unwrapping received from git top level

- Source/CarthageKit/Archive.swift
- Source/CarthageKit/FrameworkExtensions.swift
Now that `FileManager` has a `temporaryDirectory` property as of macOS 10.12, it makes sense to couple temporary directory creation logic to it.
> Extract temporary directory creation into reactive FileManager extension

- Source/CarthageKit/ScannableError.swift
`currentLine` is being printed as an optional as is, so when this description function is called 
the contents of `currentLine` are being printed as `Optional("Nirma/Attributed")` instead of just `"Nirma/Attributed"`.
I discovered this while making a mistake myself after editing my `Cartfile` so I don't think users see it often but it bugged (knee slap) me enough to send over a PR.
How does it look?
Thanks!
> [Minor Bugfix] Unwrap  currentLine  in ScannableError's description method

- Source/carthage/CopyFrameworks.swift
Duplicated input files can cause failures. Fixes #1901.
> Ensure input files to copy-frameworks are unique

- Source/CarthageKit/Project.swift
- Source/CarthageKit/VersionFile.swift
- Source/CarthageKit/Xcode.swift
- Source/CarthageKitTests/ProjectSpec.swift
- Source/CarthageKitTests/XcodeSpec.swift
- Source/carthage/Bootstrap.swift
- Source/carthage/Checkout.swift
- Source/carthage/Update.swift
Potential fix for #1905.
I was able to manually test and verify that the cache was respected for non-default toolchains by using this cartfile:
```
github "Quick/Quick" == 0.9.1
```
and this command with Xcode 8.2.1 selected (using my locally built carthage with the implemented fix):
```
.../carthage update --toolchain com.apple.dt.toolchain.Swift_2_3 --platform osx --cache-builds
```
where the stock 0.21 version of carthage did not respect the cache.
I'm not 100% certain how this can be unit tested, though. This requires either the unit tests to be run on a machine that has Xcode 8-8.2.1, or perhaps that the machine in question has a custom toolchain installed from swift.org that can be used. Is there a reasonable way to unit test this I'm not thinking of?
> Implemented toolchain-aware swift version check

- Carthage.xcodeproj/project.pbxproj
- Source/CarthageKit/Availability.swift
- Source/CarthageKit/Cartfile.swift
- Source/CarthageKit/DuplicateDependency.swift
- Source/CarthageKit/Errors.swift
- Source/CarthageKit/Project.swift
- Source/CarthageKit/Resolver.swift
- Source/CarthageKit/VersionFile.swift
- Source/CarthageKit/Xcode.swift
- Source/CarthageKitTests/CartfileSpec.swift
- Source/CarthageKitTests/DependencySpec.swift
- Source/CarthageKitTests/ProjectSpec.swift
- Source/CarthageKitTests/ResolverSpec.swift
- Source/CarthageKitTests/XcodeSpec.swift
- Source/carthage/Fetch.swift
We still refer to `Dependency`s as _projects_ in many places, but I think this is a good start.
> Rename ProjectIdentifier to Dependency

- Source/CarthageKit/Availability.swift
- Source/CarthageKit/Cartfile.swift
- Source/CarthageKit/DuplicateDependency.swift
- Source/CarthageKit/Errors.swift
- Source/CarthageKit/Project.swift
- Source/CarthageKit/Resolver.swift
- Source/CarthageKit/Xcode.swift
- Source/CarthageKitTests/CartfileSpec.swift
- Source/CarthageKitTests/ProjectSpec.swift
- Source/CarthageKitTests/ResolverSpec.swift
- Source/CarthageKitTests/XcodeSpec.swift
- Source/carthage/Extensions.swift
- Source/carthage/Fetch.swift
> Rename `project` to `dependency` for `Dependency` type

- Source/carthage/main.swift
We have some scripts that do different things based on the version of carthage they have. This allows us to roll out carthage updates across our build machines without any downtime when we uptake changes in carthage. 
Recently noticed a reversion in behavior, and it was because our usage of `carthage version` didn't work for parsing the version anymore as the warning about being out of date got in the way. It made sense to me that this sort of warning belongs in stderr, as it's not part of the 'normal' output of the command.
> Log the version warning to stderr

- Source/CarthageKit/Cartfile.swift
If we should preserve this, we should update the implementation to be consistent with `ResolvedCartfile` instead.
> [Cartfile] Remove unnecessary CustomStringConvertible conformance

- Source/CarthageKit/Xcode.swift
This is a prerequisite to static framework support. See #1379.
> Gracefully handle frameworks with no debug symbols

- .travis.yml
- Source/CarthageKit/Git.swift
There should be no need to call it for each entry of `.gitmodules`.
> Reduce unnecessary calls of `gitRootDirectoryForRepository` in `submodulesInRepository`

- .travis.yml
SwiftPM job still uses Xcode 8.2 for a while.
Once this is merged, Xcode version in the homebrew formula should be updated as well for a next release.
> Switch to Xcode 8.3

- Source/carthage/Build.swift
Resolves #1928 
There were two issues:
* The existing implementation 1) doesn't create the log file specified if it doesn't exist and 2) even if it does exist, it fails because the `FileHandle` used is immediately deallocated upon being created (so you get a Bad Descriptor exception later)
* The error handling incorrectly reported back the problem as involving the temporary directory
This PR uses the original `FileHandle` used to open the file so the resource management issue is fixed and updates the method to return a `CarthageError` so the correct error and URL can be reported.
> Fix --log-path option

- Source/CarthageKit/Xcode.swift
- Tests/CarthageKitTests/ProjectSpec.swift
- Tests/CarthageKitTests/XcodeSpec.swift
Fixes #1983 
Instead of using the language version from the swift version string, use the compiler version. That way binary compatible but different SWIFT_VERSION builds will still properly cache / be considered compatible.
> Check swift compiler

- README.md
One of the things I learned at WWDC this year is that Xcode is smart about _Run Script_ build phases if you specify both input and output files. If the input files haven't changed and the output files exist, then Xcode doesn't need to run the script again—saving you time on dirty builds.
Projects using `carthage copy-frameworks` can use this to prevent unnecessary copying of frameworks during dirty builds. This should be a nice speed boost for some projects.
A couple caveats apply:
1. Although we copy `.framework`s, `.dsym`s, and `.bcsymbolmap`s, I've only specified the `.framework`s here. I think that should be enough—it's unlikely that the other files would be removed while the `.framework` still existed.
2. This path isn't the correct path for Archive builds—they're copied to a …
> copy-frameworks Output Files

- Source/CarthageKit/FrameworkExtensions.swift
- Source/CarthageKit/Xcode.swift
Fixes #1982
Drop down to the C api for copying files so we can avoid using the APFS
cloning functionality, which has a bug that can result in invalid
binaries
> Workaround copy bug for APFS volumes

- Source/CarthageKit/Project.swift
Fixes #1969
Does a couple things
*  Move the event listener for removing the checkout folder to within the binary unarchive flatMap. This ensures it only occurs after something is actually unarchived, and not for every checkout, regardless of binary status
*  Listen for 'terminated' instead of 'completed', since the signal at this point in the operator chain will be interrupted by the later 'take' call. 
*  Use `removeItem` instead of `trashItem`. This can easily be reverted, but I saw no reason for using the trash like this. It's generally expected that command line tools will be a little less forgiving on removal of things anyway, and this appeared to be the only place we used trash
> Fix checkout removal

- Makefile
'add_rpath' doesn't work as it adds new rpath to the end of rpaths list and program will use old dylib from /Library/Frameworks instead of prefix-dir. I have production version of Carthage and developed version in prefix dir.
If I made incompatibility changes in my own Carthage version and install it to prefix dir then
$./carthage build
dyld: lazy symbol binding failed: Symbol not found: __TIFV11CarthageKit12BuildOptionscFT13configurationSS9platformsGVs3SetO6XCDBLD8Platform_9toolchainGSqSS_15derivedDataPathGSqSS_11cacheBuildsSb6activeSb_S0_A4_
Referenced from: /Users/yangand/Downloads/MyCarthage/bin/./carthage
Expected in: /Library/Frameworks/CarthageKit.framework/CarthageKit
dyld: Symbol not found: __TIFV11CarthageKit12BuildOptionscFT13configurationSS9platformsGVs3SetO6XCDBLD8Platform_9to …
> cli-prog used old dylib from /Library/Frameworks

- Makefile
make prefix_install PREFIX=<somedir>
cp -Rf "/tmp/Carthage.dst/Library/Frameworks/CarthageKit.framework" "MyCarthage/Frameworks/"
cp: cannot overwrite directory MyCarthage/Frameworks/CarthageKit.framework/Resources with non-directory /tmp/Carthage.dst/Library/Frameworks/CarthageKit.framework/Resources
> cp command failed on copying hard links if prefix_install already exists

- Source/CarthageKit/GitHub.swift
> [gardening] Avoid labeled if `break` in `Repository.fromIdentifier`.

- Source/CarthageKit/VersionFile.swift
This is a preliminary task for Xcode 9 support.
> Disambiguate Swift.Decodable and Argo.Decodable

- Makefile
Replaces both `/Library/Frameworks` and `/Library/Frameworks/CarthageKit.framework/Versions/Current/Frameworks`.
---
This is inspired by SwiftLint: https://github.com/realm/SwiftLint/blob/0.20.1/Makefile#L75-L76.
This complements #2055 and will fix #495.
/cc @norio-nomura
> [Makefile] Improve `prefix_install` rpath handling

- Source/CarthageKit/Project.swift
> [gardening] Refactor always successful `SignalProducer.attempt`s with value initializer

- Source/CarthageKit/FrameworkExtensions.swift
- Source/CarthageKit/Project.swift
- Source/CarthageKit/VersionFile.swift
- Source/CarthageKit/Xcode.swift
```swift
extension Result where Error == CarthageError {
/// Constructs a result from a throwing closure taking a `URL`, failing with `CarthageError` if throw occurs.
/// - parameter carthageError: Defaults to `CarthageError.writeFailed`.
internal init(
at url: URL,
carthageError: (URL, NSError) -> CarthageError = CarthageError.writeFailed,
attempt closure: (URL) throws -> Value
) {
do {
self = .success(try closure(url))
} catch let error as NSError {
self = .failure(carthageError(url, error))
}
}
}
```
[No functional changes (after force push)](https://github.com/Carthage/Carthage/pull/2070#issuecomment-316130854).
> [gardening] Refactor: extend Result attempting a throwing closure taking a URL, failing with `CarthageError`

- Source/CarthageKit/Cartfile.swift
- Source/CarthageKit/Constants.swift
- Source/CarthageKit/Git.swift
- Source/CarthageKit/Project.swift
No changes to API. [One (small improvement) functional change](https://github.com/jdhealy/Carthage/commit/59060edba9de865fb4e2b52cd7b007f0f251a057).
> [gardening] Refactor with `Result(attempt:)`

- Source/CarthageKit/Project.swift
Fixes bug introduced in <https://github.com/Carthage/Carthage/commit/ec4d59a#commitcomment-23208406>.
Message assuring “no functional changes” is incorrect in commit ec4d59a44351ee56d545cb0446115a0c151dc3fa.
```diff
-	do {
-		try FileManager.default.copyItem(at: url, to: destinationURL, avoiding·rdar·32984063: true)
-		return .success(destinationURL)
-	} catch let error as NSError {
-		return .failure(.writeFailed(destinationURL, error))
-	}
+	return Result(at: destinationURL, attempt: {
+		try FileManager.default.copyItem(at: url, to: $0, avoiding·rdar·32984063: true)
+		return $0
+	})
```
Accidentally introduced a functional change (moreover, a bug) by `return`ing the result’s value from a for-loop — breaking the loop and returning from the surrounding closure.
Return to previous …
> Avoid breaking for-loop on Result’s value, only break on error in `symlinkCheckoutPaths`

- Source/CarthageKit/BuildSettings.swift
- Source/CarthageKit/FrameworkExtensions.swift
- Source/CarthageKit/Git.swift
- Source/CarthageKit/ProducerQueue.swift
- Source/CarthageKit/Xcode.swift
https://github.com/ReactiveCocoa/ReactiveSwift/releases/tag/2.0.0
Related to
> `SignalProducer` resource management
and
> `SimpleDisposable` and `ActionDisposable` has been folded into `AnyDisposable`
> Preliminary task for ReactiveSwift 2.0 migration

- Tests/CarthageKitTests/ProjectSpec.swift
Lots of Travis-CI `XCTest`s from Swift Package Manager have been failing in `CarthageKitTests.ProjectSpec`.
- <https://travis-ci.org/Carthage/Carthage/jobs/259768313>
- <https://travis-ci.org/Carthage/Carthage/jobs/258303966>
- <https://travis-ci.org/Carthage/Carthage/jobs/250313794>
- - -
```diff
func buildDependencyTest(platforms: Set<Platform> = [], cacheBuilds: Bool = true, dependenciesToBuild: [String]? = nil) -> [String] {
-				var builtSchemes: [String] = []
-
let project = Project(directoryURL: directoryURL)
let result = project.buildCheckedOutDependenciesWithOptions(BuildOptions(configuration: "Debug", platforms: platforms, cacheBuilds: cacheBuilds), dependenciesToBuild: dependenciesToBuild)
.flatten(.concat)
.ignoreTaskData()
.on(value: { project, scheme in
NSLog("Building …
```
> [Tests] Remove `var`, collect schemes in `buildDependencyTest`.

- Source/CarthageKit/FrameworkExtensions.swift
> `NSTextCheckingResult.range(at:)` is only available in Swift 4 (not in Swift 3.2)

- Source/CarthageKit/Project.swift
- Source/CarthageKit/Xcode.swift
- Source/XCDBLD/XcodeVersion.swift
- XCDBLD.xcodeproj/project.pbxproj
This would make it enable to remove `clean` action from `xcodebuild clean build`.
This would also address #1469 and #2062. See also #1419.
> [PoC] Split derived data directory by Xcode version

- Makefile
- Ensure first and only parameter is non-null, contains more than whitespace, non-root if resolving absolutely.
- Ignore potential `zsh` files (except for `/etc/zshenv` — as of 5.3.1 cannot be overridden/ignored), see <http://zsh.sourceforge.net/Doc/Release/Files.html>.
- Rename possibly user-set temporary folder, which gets removed recursively.
- With prefix, less likely to have a variable by this name leftover, still-set from some previous script from whatever source.
Credit to and thanks to @zhongwuzw
See https://github.com/Carthage/Carthage/pull/2098 for discussion and potential future work.
Once again, massive, massive apologies to anyone affected.
```make
TEMPORARY_FOLDER?=/tmp/MyProject.dst
ZSH_COMMAND := ZDOTDIR='/var/empty' zsh -o NO_GLOBAL_RCS -c
RM_SAFELY := $(ZSH_COMMAND) '[[ …
```
> [Makefile] Add safety to `rm -rf` with `zsh` command

- Source/carthage/Extensions.swift
macOS deployment target was already bumped to 10.10 in #1197.
> [gardening] Remove obsolete macOS version check

- Source/CarthageKit/GitURL.swift
- Tests/CarthageKitTests/GitURLSpec.swift
Formerly relative paths are parsed as the scp syntax.
> [GitURL] Fix relative path handling in `normalizedURLString`

- Source/CarthageKit/Project.swift
- Source/CarthageKit/Resolver.swift
- Tests/CarthageKitTests/ResolverSpec.swift
Precursor to #2122 
I'd recommend viewing the diff with `?w=1`, since an extra level of indentation got added to the tests, but the differences are not actually that large.
> Update resolver signature and update/add tests

- Source/CarthageKit/Git.swift
- Source/CarthageKit/Project.swift
Specifically for the case of `../some-repo`. Formerly `cloneOrFetch` fetches a repository itself as its remote in that case because of the given `GitURL` of `../some-repo`.
In short, running the following command within `~/Library/Caches/org.carthage.CarthageKit/dependencies/some-repo` is the problem.
```bash
/usr/bin/env git fetch --prune --quiet ../some-repo refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/*
```
We should be able to use the `origin` remote instead of `../some-repo` here.
Fixes #968.
> Fix fetching a local repository with relative path

- Source/CarthageKit/Cartfile.swift
- Tests/CarthageKitTests/DependencySpec.swift
Hi,
I look at PR #2140 for #1853 and see that I can help
Like requested in #1853, json file with this PR could be accessed through file URL
I make unit test, and also see that downloading the json file is already tested, because the one used in test (successful.json) is in `Bundle`
> [BinaryProject] Add `file` scheme support in `Dependency`  #1853

- Carthage.xcodeproj/xcshareddata/xcschemes/carthage.xcscheme
This seems like a better default. Also, we only run `swiftlint` in Debug.
> Set the Run configuration in Xcode to Debug

- Source/CarthageKit/BuildSettings.swift
- Source/CarthageKit/Xcode.swift
- Source/XCDBLD/BuildArguments.swift
- Source/XCDBLD/SDK.swift
Should fix #2056.
See also https://developer.apple.com/library/content/qa/qa1964/_index.html.
> Use `archive` action when building device SDKs to disable LLVM Instrumentation

- Source/CarthageKit/Xcode.swift
To prevent built frameworks from being deleted from derived data folder.
Fixes #2207, fixes #2208.
> Set `SKIP_INSTALL=YES` when running `archive` action

- Source/carthage/Outdated.swift
This PR implements #2103
It adds an option `--xcode-warnings` to the `outdated` command to instruct it to output messages that Xcode will treat as warnings:
> Add option to Outdated to output Xcode-compatible warnings

- Source/CarthageKit/Xcode.swift
If you specify the current directory (`./`) for `-archivePath` option, `[CURRENT_DIR_NAME].xcarchive` is generated in that parent directory. For example, supposing the current directory is `~/Desktop/Carthage/`, `-archivePath ./` would generate `~/Desktop/Carthage.xcarchive`.
This is because `-archivePath` option's argument is always interpreted as a file path even that is an existing directory path. For example, supposing there is a directory `~/Desktop/Carthage/Build/`, `-archivePath ./Build/` would generate `~/Desktop/Carthage/Build.xcarchive` (if current directory is `~/Desktop/Carthage/`).
See `IDEArchivePathOverride` in the console for how `-archivePath` option would be actually interpreted by `xcodebuild`.
This is more problematic when creating a prebuilt framework using `carthage …
> Fix that `.xcarchive` is generated in parent directory of working directory

- Source/CarthageKit/Git.swift
This is a strange bug I've encountered: 
Carthage failed, but the failure message was printed incompletely:
Turns out, the reason was, that the task description contained the string terminator `\0`. Thats the reason the rest of the error message is not printed:
After some digging, I found out that the string terminator is introduced when searching for the repository url of submodules, and if I run the command manually in the terminal, it is printed as well:
I wanted to catch this as soon as possible and not just when printing the error, so this change string returned by `launchGitTask`. Not sure if this could also happen for other commands and if this should be applied at other places as well....
> Strip string terminator from result of git command

- Source/carthage/Formatting.swift
- Source/carthage/Outdated.swift
This builds on top of #2254 and includes color output to the `outdated` command to make it easier to read:
**green** for dependencies that can be updated to the latest version
**yellow** for dependencies that can be updated, where the latest update is not compatible
**red** for outdated dependencies where no compatible update is available.
> Outdated Colors

- Documentation/VersionFile.md
`xcodeVersion` has been removed with https://github.com/Carthage/Carthage/commit/0e621aae71e68b40566d6a4530f44c4525fe0337.
> Update version file doc

- Source/CarthageKit/Project.swift
From ReactiveSwift v2 it automatically gets interrupted when observer is deallocated.
> No longer need to send completed

- Source/CarthageKit/Project.swift
- Source/carthage/Outdated.swift
This PR resolves an issue on master branch that `carthage outdated` fails when git ref is used in Cartfile and no release exists for dependency.
> [Bug] Fix a bug that carthage outdated fails

- Source/CarthageKit/Xcode.swift
Currently, on large workspaces, one xcodebuild process is spawned per scheme. This saturates the build host with xcodebuild processes.
This is a proposal to limit the max number of xcodebuild processes to 4 at the buildSettings resolution step.
> Limit parallelism in discovery of build settings

- Source/XCDBLD/SDK.swift
- Tests/XCDBLDTests/SDKSpec.swift
- XCDBLD.xcodeproj/project.pbxproj
Fixes #2345 where the actual problem is that `otool` produces a mix of valid `Platform` and `SDK` string raw values.
Eg. 
```
otool -lv Carthage/Build/Mac/VSCCrypto.framework/VSCCrypto  | grep LC_VERSION
cmd LC_VERSION_MIN_MACOSX
otool -lv Carthage/Build/iOS/VSCCrypto.framework/VSCCrypto  | grep LC_VERSION
cmd LC_VERSION_MIN_IPHONEOS
otool -lv Carthage/Build/watchOS/VSCCrypto.framework/VSCCrypto  | grep LC_VERSION
cmd LC_VERSION_MIN_WATCHOS
cmd LC_VERSION_MIN_WATCHOS
```
But for tvOS...
```
otool -lv Carthage/Build/tvOS/VSCCrypto.framework/VSCCrypto  | grep LC_VERSION
cmd LC_VERSION_MIN_TVOS
```
which is awkward since following convention this should be `LC_VERSION_MIN_APPLETVOS`
or the other ones should be MACOS, IOS, WATCHOS
> Add aliases for SDK rawValue

- Source/CarthageKit/Xcode.swift
- Source/carthage/Archive.swift
When building a large project, like the FB SDK, Carthage would initially check for the buildability of each scheme of each project, then filter to only build what was exposed on on the main workspace.
This change attempt to reduce the number of xcodebuild calls by first collecting all possible shared schemes, then letting the xcworkspace filtering to the magic in order to reduce of work being done.
> Only check for buildables schemes once workspace filter has occured

- Source/CarthageKit/Xcode.swift
- Source/carthage/CopyFrameworks.swift
- Tests/CarthageKitTests/XcodeSpec.swift
Strip debug symbols when copying frameworks using "carthage copy-frameworks" if COPY_PHASE_STRIP is enabled.
Now "carthage copy-frameworks" behaves the same as vanilla Xcode copy task as far as debug symbols go.
See PR #2334 for full discussion on why this is a good thing.
> Strip debug symbols when copying frameworks using "carthage copy-frameworks"

- Source/CarthageKit/Project.swift
- Source/CarthageKit/Xcode.swift
- Source/carthage/Build.swift
- Tests/CarthageKitTests/ProjectSpec.swift
- Tests/CarthageKitTests/XcodeSpec.swift
This prevents us from polluting those dependencies with a `Carthage/` directory. (This can be annoying if you're using submodules and they haven't ignored that directory.)
> Don't create Carthage/Build symlink if project doesn't use Carthage

- .swiftlint.yml
- Source/CarthageKit/BinaryProject.swift
- Source/CarthageKit/BuildOptions.swift
- Source/CarthageKit/Errors.swift
- Source/CarthageKit/Git.swift
- Source/CarthageKit/Project.swift
- Source/CarthageKit/Resolver.swift
- Source/CarthageKit/Xcode.swift
- Source/XCDBLD/Platform.swift
- Source/XCDBLD/SDK.swift
- Source/carthage/Archive.swift
- Source/carthage/CopyFrameworks.swift
- Tests/CarthageKitTests/XcodeSpec.swift
Some clean up of the compilation warnings. Most of this is either adding `swiftlint:disable` hints or resolving the issue.
In collaboration with @mdiep, I disabled 2 rules in `.swiftlint.yml` definition.
I also removed conformance to `CustomStringConvertible` for `Platform` as it only returned the `rawValue` and the call site was accessing `description` directly, which defeats the purpose of the protocol. I updated the call site to use `rawValue` directly. I added a test around this to make sure nothing changed.
> Resolve all swiftlint violations.

- Source/CarthageKit/VersionFile.swift
This is my attempt in fixing the issue discussed in #2375. Thanks @blender for consultations! 
Basically the code was converted from capturing and sharing `platformCaches` dictionary to reducing the results of calculating all hashes to a single dictionary. It is then used to initialize `VersionFile` as before.
This is my first time working with a ReactiveSwift codebase, so I am not sure if I followed all the good practices. Things I think could be improved:
* `createVersionFile` function doesn't do that much but has many parameters...
* Nested tuple in `SignalProducer<(String, (String, String)), CarthageError>`. My first try was passing down `url` instead of `(frameworkName, platformName)`, but then I need to calculate `frameworkName` two times.
Let me know what you think!
> Fix for segmentation fault when bootstrapping

- Source/CarthageKit/Xcode.swift
Fixes #2369.
This broke in #2344. The check for whether a scheme should be built needs to occur against the project it's from, not against the workspace that includes it.
cc @jdhealy @allenhumphreys
> Check if schemes are buildable with projects, not workspaces

- Documentation/StaticFrameworks.md
I encountered some linker warnings after following the instructions here, and wanted to provide information on a workaround.
I think this would be ultimately solved by somehow providing a custom modulemap for the larger dynamic framework that defines correct modules for each of the static frameworks that make it up, but that's beyond me at the moment.
> Provide information on linker warning workaround for static framework script

- Documentation/Artifacts.md
As there is a lot of binary framework developers that call their specification file Carthage.json, updating frameworks becomes difficult and confusing
Updating those frameworks needs the command `carthage update Carthage` that first sounds weird, but also does update all binary dependencies with this same specification name.
> JSON specification file name recommendation for binary projects

- Tests/CarthageKitTests/VersionSpec.swift
At the moment, Carthage does not comply with the [semantic versioning](https://https://semver.org/) specifications for pre-release versions, build number versions and non-semantic versions.
This PR aims to document this non-standard behavior. In a following PR, I will make Carthage comply with the semantic versioning specifications and I can invert the logic of these tests.
I explicitly marked the tests that are highlighting the non-standard behavior with the following comment:
> `/// The following behavior does not follow the SemVer <https://semver.org/> specifications`
> Expand `VersionSpec` tests to include pre-release and non-semantic versions

- .travis.yml
- Source/CarthageKit/Version.swift
- Tests/CarthageKitTests/VersionSpec.swift
According to [SemVer specs](http://semver.org), pre-release and build metadata are valid components of a version specification. Adding support for then in the version parser.
This PR is derived from the work on https://github.com/Carthage/Carthage/pull/1553, and it's the first of the tree discussed there.
>  Add support for pre-release and build metadata, as per SemVer specs

- Source/CarthageKit/Version.swift
- Tests/CarthageKitTests/VersionSpec.swift
This commit introduces the logic for comparison of pre-release versions and versions with build metadata.
For the purpose of comparison:
- pre-release versions follow the specifications at http://semver.org/
- build metadata is ignored when performing comparisons
For the purpose of intersection of requirements (i.e. find a version that satisfies two requirements):
- pre-release versions follow the specifications at http://semver.org/
- build metadata is ignored when using a `.atLeast`, `.any` or `.compatibleWith` requirement, but taken into account when using an `.exactly` requirement.
> Implement comparison and intersection of pre-release and build versions

- Source/CarthageKit/Dependency.swift
- Source/CarthageKit/Project.swift
- Tests/CarthageKitTests/DependencySpec.swift
- Tests/CarthageKitTests/ProjectSpec.swift
PR https://github.com/Carthage/Carthage/pull/2360 which allows anyone to update and install required binaries via relative path. BUT.. once installed, the resolved file is tied to a user specific filepath
`carthage update` with current relative implementation works... but leaves an absolute file path for binary json specs, which will fail on others computers
`carthage bootstrap` fails if not run on computer which ran update b/c path is not going to be the same.
Cartfile
```
binary "CarthageSpecs/AppboyFramework.json"
```
Cartfile.resolved
```
binary "file:///Users/dmiluski/code/folder/CarthageSpecs/AppboyFramework.json" "3.3.2"
```
This means the resolved file path would only work on the original computer used to run.
binary urls should appear the same for both Cartfile & …
> [BinaryProject] Relative Path Cartfile.resolved Support

- Source/CarthageKit/Proxy.swift
- Tests/CarthageKitTests/ProxyTests.swift
> Use just the host part of the URL for proxy values, drop the scheme

- README.md
I found my build error was because I quickly skimmed the README. I have updated the README to stop another from doing the same. Specifically, I changed "e.g." to the more explicit synonym, "For example". I find it clearer.
> Minor change to make the README examples standout

- Source/carthage/Extensions.swift
This would clarify the intention of the error (actually an warning) and help users to understand what will happen after the error.
How does this look like?
> Try to improve `skippedInstallingBinaries` error message

- Source/CarthageKit/Version.swift
- Tests/CarthageKitTests/VersionSpec.swift
Any version with `-` but without pre-release, or with `+` but without build metadata, is discarded as invalid
> Discard invalid build metadata and pre-release semantic version

- Source/carthage/Archive.swift
- Source/carthage/Build.swift
- Source/carthage/Update.swift
Fixes #1411. 
To be honest I just finished the works by @3lvis so credits to him for starting that one 😉
> Add --archive option to the build command.

- Source/CarthageKit/FrameworkExtensions.swift
This PR resolves issue #2444.
Our archive build steps for a macOS application were failing when doing the `carthage copy-frameworks` step due to a problem with code signing. The error message shown in the log was:
[…]/Contents/Frameworks/Result.framework: bundle format is ambiguous (could be app or framework)
However, the real problem was that the framework has not been copied at all and therefore `codesign` had nothing to sign at the destination path.
The `copyItem` method in `FrameworkExtension.swift` contains a workaround for copying files on an APFS disk and it falls back to the `copyFile` function from the standard c lib instead of using `NSFileManager`.
When executing an archive step on macOS, the `to` target resolves to a symlink: …
> To destination is a symlink when archiving on macOS

- Source/CarthageKit/Xcode.swift
- Tests/CarthageKitTests/XcodeSpec.swift
With this and #1932 we should be able to fully support static frameworks.
Should resolve #1379.
> [WIP] Support building static frameworks

- Source/CarthageKit/Version.swift
- Tests/CarthageKitTests/CartfileSpec.swift
- Tests/CarthageKitTests/Resources/TestCartfile
- Tests/CarthageKitTests/VersionSpec.swift
According to https://git-scm.com/docs/git-check-ref-format, whitespace are not allowed in a tag, commit SHA, or branch name, so I assume the version ends at the first space.
The reason for this code change is that inline comments in the Cartfile (`#...`) should not be parsed as part of the semantic version. Since comments should at least have a space before the `#` (because otherwise they could be considered part of the commit-ish, `head/foo#2` is a valid tag for example).
I decided to use spaces to identify comments. If there is a space and it's not followed by a comment, the file parser will throw an error because it expects either a comment or the line to be over.
> Ignore anything after a space when parsing semantic versions

- Source/CarthageKit/Version.swift
- Tests/CarthageKitTests/VersionSpec.swift
This commit implements validation of pre-release and build metadata according to SemVer specifications (https://semver.org/):
> [pre-release and build metadata] identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]
Additionally, for pre-release
> [...] MAY be denoted by appending a hyphen and a series of dot separated identifiers.  [...]  Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes.
> Stricter validation of pre-release and build metadata according to SemVer

- Source/CarthageKit/Version.swift
- Tests/CarthageKitTests/VersionSpec.swift
As mentioned here https://github.com/Carthage/Carthage/pull/2453#discussion_r189330964, `CharacterSet.decimalDigits` contains some characters that should not be parsed as valid version
> Discard fullwidth digits in semver parsing

- Source/CarthageKit/Cartfile.swift
- Source/CarthageKit/Version.swift
- Tests/CarthageKitTests/Resources/TestCartfile
- Tests/CarthageKitTests/VersionSpec.swift
Previously, the code was relying on there being a space between a version specified and a comment. This commit removes that assumption.
> Use `#` token for comment detection instead of space when parsing semver

- Source/CarthageKit/Constants.swift
- Source/CarthageKit/Project.swift
Sometimes framework.zip files (created with `carthage archive`) are uploaded with the incorrect MIME type. For example, if the archives are uploaded with the `github-release` utility, they end up with a MIME type of `application/octect-stream` instead of `application/zip`. 
This patch supports archives with a `.zip` extension but which may not have the expected MIME type.
> Allow binary assets with .zip extension.

- Source/CarthageKit/Version.swift
Refactor `Scanner.scanStringWithPrefix` with `prefix` as `Character`.
Refactor `Scanner.remainingString` → `Scanner.remainingSubstring` which returns an optional.
See code comments and <https://twitter.com/UINT_MIN/status/968200980599746560>.
> Fix errant UTF-16 offset use by ranging with converted `NSRange`.

- Carthage.xcodeproj/project.pbxproj
- Source/CarthageKit/Cartfile.swift
- Source/CarthageKit/Version.swift
- Tests/CarthageKitTests/CartfileCommentsSpec.swift
- Tests/CarthageKitTests/VersionSpec.swift
Having the detection of Cartfile comments inside the version parser makes the parser unnecessarily tied to the Cartfile syntax. Additionally, since there is no case in which we would parse a version specifier and not ignore the comments, either we have to live with a parameter that is always set to `true` in the entire codebase, or remove the parameter and make strong assumptions on how the version parsing is used.
This PR moves comment filtering to the Cartfile parsing code. Comments are stripped from each line before passing lines to the version parser.
The detection of comments is done with the following strategy:
- any `#` character that is not inside "quotes" is considered the beginning of the comment
- for the purpose of determining whether a character is inside quotes, the code …
> Refactor detection of Cartfile comments

- Documentation/StaticFrameworks.md
This pull request adds extra workaround that addresses issue https://github.com/Carthage/Carthage/issues/2442.
Project where you can check described behaviour can be found [here](https://github.com/dimazen/static-linking).
> Add additional StaticFrameworks linker workarounds

- Source/CarthageKit/VersionFile.swift
This fixes the error, "Raw type 'String' must appear first in the enum inheritance clause".
> Fix build error with Xcode 10

- Source/carthage/CopyFrameworks.swift
Fixes <https://github.com/Carthage/Carthage/issues/2472>.
Treat `EXPANDED_CODE_SIGN_IDENTITY` — when `EXPANDED_CODE_SIGN_IDENTITY` is unset and `XCODE_PRODUCT_BUILD_VERSION` is set — with the same behavior as having empty string.
Xcode beta release `10L176w` (and potentially more) seem to omit environment variables set to an empty string in Run Script Phases (and potentially other places). So with the heuristic of `XCODE_PRODUCT_BUILD_VERSION` being set signifying a Run Script Phases (or other within Xcode scenario), ignore the error by returning `nil`, as is done when `codeSigningAllowed()` is false.
Credit and thanks to @clayellis for reporting the behavior change and [iterating on code changes](https://github.com/Carthage/Carthage/pull/2473).
> Consider `XCODE_PRODUCT_BUILD_VERSION` alongside `EXPANDED_CODE_SIGN_IDENTITY` to address Xcode 10 beta.

- Carthage.xcodeproj/project.pbxproj
- Source/CarthageKit/FrameworkExtensions.swift
- Source/CarthageKit/MachHeader.swift
- Source/CarthageKit/Project.swift
- Source/CarthageKit/VersionFile.swift
- Source/carthage/Archive.swift
- Tests/CarthageKitTests/MachHeaderSpec.swift
- Tests/CarthageKitTests/ProjectSpec.swift
Some frameworks don't have `Info.plists` and are being currently rejected as binary dependencies.
This PR addresses #2500 and also makes sure that .version files are written.
> Use `objdump` to determine whether a binary blob from a compressed archive should be handled by Carthage

- README.md
Add a notice and the description of static framework support being introduced into the project's features.
Resolves #2497 .
> Static frameworks support information in README.

- .travis.yml
<blockquote>
[Homebrew](https://github.com/Homebrew/brew/)’s [bottling process](https://github.com/Homebrew/brew/blob/0c38ceb6f6b0dd6fd2120b5bea8ea979c076d2ab/docs/Bottles.md) for binaries they distribute [has a table matching Xcode versions with each bottle-build-hosting macOS version](
https://github.com/Homebrew/brew/commit/595c23286663009086509d9bdfbfa9b172d43fe5#diff-c170234aefab4dfe656ce6e8fccb4351)
[Currently](https://github.com/Homebrew/brew/commits/master/Library/Homebrew/os/mac/xcode.rb) — based on our requirement of Xcode 9+ — bottles build with Xcode 9.2 and 9.4, so our [`travis.yml` ](https://github.com/Carthage/Carthage/blob/3de4ab8ea7e24a52f0e5e71dbc8311428fd9c899/.travis.yml) should have both those `osx_image`s.
</blockquote>
Fixes #2508.
> [CI] Use Xcode 9.4 image alongside Xcode 9.2.

- Source/CarthageKit/Version.swift
- Tests/CarthageKitTests/VersionSpec.swift
The code was incorrectly parsing invalid [SemVer](https://semver.org) version that contained too many dots (e.g. `1.8.0.1` or `1.8..1`) as valid.
This PR adds unit test to highlight those cases, and fixes the issue.
>  Fix SemVer parsing with too many dots

- README.md
[0.30.1](https://github.com/Carthage/Carthage/releases/tag/0.30.1) introduces a simpler way of archiving. The command was introduced in https://github.com/Carthage/Carthage/pull/2438 and it works great!
```
carthage build --archive
```
> Improve instructions for prebuilding frameworks

- Source/CarthageKit/BuildSettings.swift
0.30.1 now fails to build Facebook SDK as it tries to archive scheme which is not configured for.
```
xcodebuild: error: Scheme FBSDKIntegrationTests is not currently configured for the archive action.
```
To fix this, updated to get build settings using `archive` action instead to determine if it's available or not.
```
$ carthage checkout
$ rm -f ./Carthage/Checkouts/facebook-ios-sdk/FBSDKIntegrationTests/FBSDKIntegrationTests.xcodeproj/xcshareddata/xcschemes/FBSDKIntegrationTests.xcschem
$ carthage build
```
> Use archive action instead to load build settings

- README.md
> [Docs] Add warning to not use `copy-frameworks` in non-applications

- Source/CarthageKit/Xcode.swift
This would fix #2491 (should work for frameworks who does not contain the `Info.plist` file).
> Use `Bundle.executableURL` instead of `object(forInfoDictionaryKey: "CFBundleExecutable")`

- Source/CarthageKit/Archive.swift
our framework is provided as tar.xz. Carthage tries to unzip it, this correctly untars it
> [Archive] add xz to the supported pathExtensions for untar

- Source/carthage/Build.swift
The description of the `-no-use-binaries option` doesn't look correct:
```
[--no-use-binaries]
use downloaded binaries when possible
```
Updated with `don't use downloaded binaries when possible`.
> Updated documentation of the --no-use-binaries option

- Source/CarthageKit/Project.swift
Carthage creates a symlink to the main Build folder from the Carthage directory of each dependency.  However, these symlinks are created in the process of building each dependency, and as a result they are not created for binary downloads (which are not built by Carthage).  This PR fixes this inconsistency.
I am not sure if this change will be useful for normal Carthage users; however, it would be useful for my team as our project has two workspaces, one of which includes the contents of Carthage/Checkout as sub-projects.  Xcode needs all of the Build folders to be symlinked in order to build the project.
I would appreciate advice as to how this change could be tested.  As far as I can tell there are currently no tests that verify the Build symlinks are created, nor tests that check out a …
> Symlink the Build folder for binary downloads

- Tests/CarthageKitTests/ValidateSpec.swift
That will be problematic (especially on Swift 4.2 or later).
Ref: #2523
> [ValidateSpec] Don't rely on a dictionary's order

- Source/CarthageKit/Simulator.swift
- Tests/CarthageKitTests/Resources/Simulators/availables-xcode101.json
- Tests/CarthageKitTests/Resources/Simulators/availables.json
- Tests/CarthageKitTests/SimulatorSpec.swift
closes #2602 
[carthage build command complains about "Could not find any available simulators for iOS" · Issue #2602 · Carthage/Carthage](https://github.com/Carthage/Carthage/issues/2602)
Since Xcode 10.1 beta, Structures of `xcrun simctl list devices --json` is changed.
```json
{
"devices" : {
"iOS 12.0" : [
{
"state" : "Shutdown",
"availability" : "(available)",
"name" : "iPhone 5s",
"udid" : "A52BF797-F6F8-47F1-B559-68B66B553B23"
}
]
}
```
```json
{
"devices" : {
"iOS 12.0" : [
{
"state" : "Shutdown",
"isAvailable" : "YES",
"name" : "iPhone 5s",
"udid" : "A52BF797-F6F8-47F1-B559-68B66B553B23"
}
]
}
```
Because of this changes, parsing on Xcode 10.1 is failed.
I extended the parsers to be possible parsing results of `simctl` on Xcode 10.1.
It will work on any Xcode versions.
> Fix the issue can't find available simulators on Xcode 10.1 beta

- Source/CarthageKit/Simulator.swift
- Tests/CarthageKitTests/Resources/Simulators/availables-xcode101-beta.json
- Tests/CarthageKitTests/Resources/Simulators/availables-xcode101.json
- Tests/CarthageKitTests/SimulatorSpec.swift
Xcode 10.1 release has broken available simulators. Everything ended with the error
```
Could not find any available simulators for iOS
```
The cause was that Apple already knows that `Bool` exists. This is already mentioned in https://github.com/Carthage/Carthage/pull/2606#issuecomment-434440690.
The change is designed to maintain backwards compatibility with the 10.1 beta releases.
> Fix Xcode 10.1 available simulators

- Source/CarthageKit/SwiftVersionError.swift
- Source/CarthageKit/VersionFile.swift
- Source/CarthageKit/Xcode.swift
- Tests/CarthageKitTests/ProjectSpec.swift
- Tests/CarthageKitTests/XcodeSpec.swift
See https://github.com/Carthage/Carthage/issues/2619 for reference.
This PR only implement the first fallback.
> Fall back to get swiftlang & clang version from dSYM 

- Source/CarthageKit/Git.swift
Otherwise each submodule syncs all submodules. For projects using submodules with large numbers of dependencies, which may themselves have a large number of submodules, this can save quite a bit of time.
Tested on a project locally:
```
» time carthage checkout --use-submodules    
*** Checking out ReactiveCocoa at "8.0.0"
*** Checking out ReactiveSwift at "4.0.0"
*** Checking out Schemata at "0.2.0"
*** Checking out PersistDB at "ab564f1f91964c5e4f02bd790a454ce950ccb5cb"
*** Checking out Result at "4.0.0"
*** Checking out Differ at "1.3.0"
*** Checking out Anchorage at "4.3"
*** Checking out Standards at "89c30330fcac972a84a4876125064001b9c89f0f"
carthage checkout --use-submodules  2.49s user 2.87s system 99% cpu 5.386 total
» time carthage-dev checkout --use-submodules
*** Checking out …
```
> Sync submodules from the submodule directory

- Source/CarthageKit/BinaryProject.swift
- Source/CarthageKit/CompatibilityInfo.swift
- Source/CarthageKit/Dependency.swift
- Source/CarthageKit/DuplicateDependency.swift
- Source/CarthageKit/ScannableError.swift
- Source/CarthageKit/Submodule.swift
- Source/CarthageKit/SwiftVersionError.swift
- Source/CarthageKit/Version.swift
- Source/carthage/Build.swift
Remove an unused protocol and use synthesized `Equatable`/`Hashable` implementations where possible.
> Clean up model types

- .travis.yml
- IntegrationTests/update.bats
- Package.resolved
- Package.swift
- Source/CarthageKit/BinaryProject.swift
- Source/CarthageKit/CarthageKitVersion.swift
- Source/CarthageKit/CompatibilityInfo.swift
- Source/CarthageKit/NewResolver.swift
- Source/CarthageKit/Project.swift
- Source/CarthageKit/RemoteVersion.swift
- Source/CarthageKit/Resolver.swift
- Source/CarthageKit/Simulator.swift
- Source/CarthageKit/Version.swift
- Source/carthage/RemoteVersion.swift
- Tests/CarthageKitTests/CartfileSpec.swift
- Tests/CarthageKitTests/DB.swift
- Tests/CarthageKitTests/RemoteVersionSpec.swift
- Tests/CarthageKitTests/ValidateSpec.swift
- Tests/CarthageKitTests/VersionSpec.swift
Depends on #2665.
This is the first step in building more off of SwiftPM. I think if we do this, then use their equivalent of `VersionSpecifier`, we can start reading `Package.resolved` and/or using the Swift PM resolver. Using common types will make those things easier.
> Use Version type from SwiftPM

- Documentation/Artifacts.md
I wondered where the JSON contents are explained at first, so I think a link might help those who don't just scroll all the way down when puzzled :)
> add link to binary specification JSON

- CONTRIBUTING.md
- Makefile
Adds a `make xcodeproj` `Makefile` entry that generates a working Xcodeproj (some
extra work was required for libSwiftPM), see:
https://github.com/apple/swift-package-manager/tree/master/Examples/package-info
Fixes #2692
> Fix CONTRIBUTING “make bootstrap” instructions

- Source/CarthageKit/Git.swift
The `list(treeish:atPath:inRepository:)` function was not working as expected. But this hasn't caused any actual problem since there is a further check (the `continue` statement in the `symlinkCheckoutPaths` method) afterward.
> Fix an ls-tree issue

- Source/CarthageKit/VersionFile.swift
- Source/CarthageKit/Xcode.swift
- Tests/CarthageKitTests/VersionFileSpec.swift
- Tests/CarthageKitTests/XcodeSpec.swift
> Make swiftToolchainVersion optional for ObjC only frameworks

- Package.resolved
- Package.swift
- Source/CarthageKit/BinaryProject.swift
- Source/CarthageKit/Cartfile.swift
- Source/CarthageKit/CarthageKitVersion.swift
- Source/CarthageKit/CompatibilityInfo.swift
- Source/CarthageKit/Constants.swift
- Source/CarthageKit/Git.swift
- Source/CarthageKit/NewResolver.swift
- Source/CarthageKit/Project.swift
- Source/CarthageKit/RemoteVersion.swift
- Source/CarthageKit/Resolver.swift
- Source/CarthageKit/Simulator.swift
- Source/CarthageKit/Version.swift
- Source/carthage/CopyFrameworks.swift
- Source/carthage/RemoteVersion.swift
- Tests/CarthageKitTests/CartfileSpec.swift
- Tests/CarthageKitTests/DB.swift
- Tests/CarthageKitTests/RemoteVersionSpec.swift
- Tests/CarthageKitTests/ValidateSpec.swift
- Tests/CarthageKitTests/VersionSpec.swift
Resolves #2705.
Before, we specified SwiftPM `master`. This works fine in our repo, since `Package.resolved` specifies a revision. But if you used Carthage as a dependency, it wouldn't compile.
This also updates to Result 4.1.0 and fixes the deprecation warnings from the adoption of the `Swift.Result` method names.
> Use specific SwiftPM tag

- Makefile
While toolchains such as `swift-5.0-DEVELOPMENT-SNAPSHOT-2019-03-24-a` still contain a `…/usr/lib/swift_static` directory, some Xcode 10.2 bundles do not.
Swift Package Manager maintains compiling in the Swift standard library into executables [statically by default][1].
[1]: https://github.com/apple/swift-package-manager/commit/c886c8e4fcba2aec5d6b7dccf8d40afc5951293d
> Swift Package Manager: Accommodate any swift toolchain without a `swift_static` directory for the standard library

- Source/CarthageKit/Xcode.swift
This is meant to fix merging Swift header files for Xcode 10.2 by adding missing include directive for `TARGET_OS_SIMULATOR` definition.
- Xcode doesn't set `TARGET_OS_SIMULATOR` value by default and shows `undeclared identifier` errors at compilation for the symbols in generated Swift header file.
- Including `TargetConditionals.h` to the header file solves the issue.
Generated Swift header file should now look like this:
```
#include <TargetConditionals.h>
#if TARGET_OS_SIMULATOR
<simulator Swift.h>
#else
<device Swift.h>
#endif
```
Coauthored with @buranmert
Related: https://github.com/Carthage/Carthage/pull/2723
> Fix merging Swift header files for Xcode 10.2

- Source/CarthageKit/Dependency.swift
- Source/CarthageKit/GitURL.swift
- Source/CarthageKit/NewResolver.swift
- Source/CarthageKit/Resolver.swift
- Source/CarthageKit/Xcode.swift
Use `func hash(into:)` to avoid warnings on Xcode 10.2.
This PR make all warnings from CarthageKit were suppressed.
> Avoid warnings on Xcode 10.2 in CarthageKit

- README.md
Shouldn't the command there be `carthage update --platform macOS`?
Otherwise it will build the frameworks for other platforms as well.
Also, changes 'OS X' to macOS
> Readme: "If you're building for OS X"

- Source/CarthageKit/Project.swift
When downloading a binary archive that also contains a dSYM, Carthage doesn't copy that dSYM to _Carthage/Build_ unless it covers all of the architectures in the binary. So if it covers 2/4 architectures, it isn't copied.
With this PR, all dSYMs covering at least one of the architectures in the binary, are copied.
> Copy dSYMs that are incomplete

- README.md
Update to README. Small addition to the command to run `carthage outdated`. As is, if there is no network connection, it errors causing the build in Xcode to fail. This change pipes errors to dev/null silencing the warning allowing the build to succeed.
> Update to README. Pipe `carthage outdated` errors to dev/null

- README.md
- Source/CarthageKit/Errors.swift
- Source/CarthageKit/Project.swift
- Source/CarthageKit/XCDBLDExtensions.swift
See #2764 in which the archive contains "TealiumIOS.framework" multiple times.
> Reject archives containing duplicated framework names

- Source/CarthageKit/FrameworkExtensions.swift
- Source/CarthageKit/Xcode.swift
When stripping frameworks, copy the source into a temporary directory, process it there, and then move it back.
This is a rework of my previous PR, which didn't actually do what I thought it did.
> Bugfix 2788

- README.md
This PR adds documentation about the `xcfilelist`s that were introduced during WWDC18.
I think it´s easier to modify or automate the modification of these dependency declaration if they are in a dedicated file.
> Add .xcfilelist documentation

- README.md
The snippet in **README.md** to add to the build phase is wrong by one pipe (`|`)
I'm not sure what a pipe does in this scenario, but it is not the right thing. Bash seems to take `echo "foo" | 2>/dev/null` and alias 2 to be a `cd` command. If one wants to redirect `stderr` to **/dev/null**, one only needs `2>/dev/null`. Before this change. all the output from the outdated dependencies step is swallowed and nothing gets added to Xcode. After, the warnings will show up in the console, but no network connection doesn't cause build failures (https://github.com/Carthage/Carthage/commit/70f5b2c51c78fb5440155346063f792347c893d9#diff-04c6e90faac2675aa89e2176d2eec7d8)
> Remove pipe in carthage outdated step

- .travis.yml
- Makefile
- Package.resolved
- Package.swift
[swift-llbuild](https://github.com/apple/swift-llbuild.git)'s Package.swift was updated to Swift 5. This in combination with `swift build` __automatically updating dependencies__ prevents carthage from building with SwiftPM.
First, to stop SwiftPM from updating dependencies, it is necessary to add `--skip-update`.
Unfortunately however that's not enough for carthage to build. SwiftPM itself [adds a very nasty dependency to swift-llbuild master](https://github.com/apple/swift-package-manager/blob/916450f7e8a5aef13630edf9e6fc0b16ed9f5f65/Package.swift#L262)
To prevent that from happening it's enough to set `SWIFTPM_BOOTSTRAP` environment variable, however this completely removes swift-llbuild from the dependency graph.
To keep swift-llbuild in the dependency graph it's necessary to add it …
> Fix building with SPM

- Source/CarthageKit/Project.swift
This problem is introduced by #2795.
Cartfile to reproduce the problem:
```github "ReactiveCocoa/ReactiveSwift" == 5.0.0```
First, run a `carthage update --no-build` to make sure cache repositories are cloned. Then remove `~/Library/Caches/org.carthage.CarthageKit/dependencies/Result`, and run a `carthage checkout`. It will get an error when cloning `Result`.
The reason is that carthage will `checkoutOrCloneDependency` for all dependencies concurrently meaning it will checkout ReactiveSwift and clone Result at the same time. After ReactiveSwift is checked out, carthage will fetch the Result submodule of ReactiveSwift conflicting with the cloning of Result dependency.
The solution is to delay the checkout after all dependencies are fetched, and submodules should be dealt serially.
Most …
> Fix fetching race condition

- Source/carthage/Update.swift
Workaround for #2831.
I've created a [Swift bug](https://bugs.swift.org/browse/SR-11423) for this crash, but I figure it probably won't be fixed in time for Xcode 11 GM.
> Add workaround for Swift 5.1 compiler crash

- Makefile
- Package.resolved
- Package.swift
- Source/CarthageKit/BinaryProject.swift
- Source/CarthageKit/CarthageKitVersion.swift
- Source/CarthageKit/CompatibilityInfo.swift
- Source/CarthageKit/NewResolver.swift
- Source/CarthageKit/Project.swift
- Source/CarthageKit/RemoteVersion.swift
- Source/CarthageKit/Resolver.swift
- Source/CarthageKit/Simulator.swift
- Source/CarthageKit/Version.swift
- Source/carthage/RemoteVersion.swift
- Tests/CarthageKitTests/CartfileSpec.swift
- Tests/CarthageKitTests/DB.swift
- Tests/CarthageKitTests/RemoteVersionSpec.swift
- Tests/CarthageKitTests/ValidateSpec.swift
- Tests/CarthageKitTests/VersionSpec.swift
A [bug in the-tool-SwiftPM's package resolution](https://github.com/apple/swift-package-manager/pull/2197) resulted in disregard for the (crucial) ‘resolved file’ when resolving branch-based dependencies.
Which would put us in the position of needing any commit of `apple/swift-package-manager` that didn't specify its dependency on `apple/swift-llbuild` in the branch-based style.
Also criteria for the above, [working Swift 4.2.X manifests and compilation](https://forums.swift.org/t/about-reproducible-builds/26957/10) _and_ working Swift 5.X manifests and compilation.
No such commit of `apple/swift-package-manager` could be found.
In addition, some confusion around [`llbuild`'s `sqlite3` linkage](https://github.com/apple/swift-llbuild/commit/f1c9ad9a253cdf1aa89a7f5c99c30b4513b06ddb#diff-37ca …
> Remove — as a library dependency — `SwiftPM` and `llbuild` and reinstate `struct Carthage.SemanticVersion`

- .travis.yml
- Makefile
Crucial to enable Homebrew installs: due to Homebrew's own use of sandboxing.
Travis: remove `make clean` and `SWIFTPM_BOOTSTRAP` (`var` for certain versions of SwiftPM-as-a-library) — no longer necessary as of Carthage/Carthage@9b009cb408afb08e3b32d234adb7a8ee5f1be627.
Restores previous behavior.
Partial revert of Carthage/Carthage@60aaf683dc4e5d446c2b64704e7c02b80de45ba3.
> Swift Package Manager: Suppress `sandbox-exec` under Homebrew.

- test.json
Our exemption here is somewhat heuristic — but, it applies broadly in Xcode environments, and Swift Package Manager environments, and others.
> For users named «travis» (case-insensitively), return early in `RemoteVersionSpec` rather than expose tests to the flakey interference currently seen

- Source/CarthageKit/Constants.swift
Sometimes GitHub uses `application/x-zip-compressed` content type for zip archives. This type should be allowed as it's just a zip file.
PS: It was really tricky to figure out what was wrong with the release.
> Add alternative content type for zip archives

- Source/CarthageKit/Xcode.swift
If for instance your bundle doesn't contain a plist, the current error message says that Carthage cannot read the file or folder. The same goes for if the filename of the dSYM isn't in the correct format. So I've extended these messages.
> Extend error messages when reading binaries

- Source/CarthageKit/Git.swift
https://github.com/Carthage/Carthage/issues/2760#issuecomment-555964945
Use NSLock to coordinates the operation of multiple threads of execution within the FetchCache.
> Fix Segmentation Fault 11 while calling FetchCache.updateLastFetchTime

- Source/CarthageKit/GitURL.swift
- Tests/CarthageKitTests/DependencySpec.swift
When Cartfile contains a local dependency of which path ends with `..`, Carthage clones the repo into the wrong place.
I created the repository to reproduce the behavior: https://github.com/manicmaniac/CarthageDirectoryTraversal
`GitURL.name` doesn't check if the own path is relative or absolute but just returns the last path component.
So the name could be `..` and later it will be used as the destination path where the dependency should be copied.
I added some code to `GitURL` to convert a relative path to the absolute path before getting the name.
> Prevent directory traversal

- Makefile
Addresses Carthage/Carthage#2941
Modified the `install` make target so that the `BINARIES` directory is check for existence and create if not.
> Makefile - Check for and create binaries directory in install target

- IntegrationTests/copy-frameworks.bats
Newer versions of Xcode don't have an iPhone 6s by default so this should be a good compromise that works on older and newer versions of Xcode.
> Fix integration test that is failing on newer versions of Xcode

- Source/CarthageKit/GitURL.swift
- Tests/CarthageKitTests/DependencySpec.swift
Also, sanitize [nul characters](https://en.wikipedia.org/wiki/Null_character) in `GitURL`s (transposing them to «␀».)
The cases in the modified test are — given a URL is specified and provided is a string without URL scheme — pathological, and as such the result for them from `GitURL.name` are maybe unintuitive, but decidedly safe.
The flag «--project-directory» clashed with the formerly placed (but never shipped in a tagged Carthage release) invocation of `FileManager.currentDirectoryPath`.
To avoid the clash, we settle on a less intuitive, but most importantly safe change — _to be clear_ a *breaking change* for some pathological URL-scheme–less or nul-character–containing Cartfile lines and `GitURL`s.
> Prevent directory traversal (in more piecemeal way) allowing «project-directory» flag to function.

- Source/XCDBLD/SDK.swift
The project failed to build on Xcode 12 and macOS 11.0 due to following error:
```
/Users/eofs/Projects/Xcode/Carthage/Source/XCDBLD/SDK.swift:80:3: error: call can throw, but errors cannot be thrown out of a global variable initializer
KeyValuePairs.reduce([
^
```
This prevented installing latest Carthage release using `brew`.
Calling `reduce()` on the collection itself instead allowed the project to build successfully.
> Failed to build on Xcode 12 and macOS 11.0

- Source/CarthageKit/VersionFile.swift
This is enhancement as mentioned in #3013
Sort the frameworks by name in the version file
So we can easily identify which frameworks are altered when situations like running `--update`
> Sort frameworks in version file

- Source/CarthageKit/Project.swift
I found a cache-related bug.
I downloaded a zip file of the binary framework using Carthage, but it was failed because the zip file was broken.
So I corrected the zip file, and then I tried to download the framework.
But it occurred the same error.
The error was following:
```
*** xcodebuild output can be found in /var/folders/z3/lyh75tws0hg4nsp2wrg6gxnw0000gq/T/carthage-xcodebuild.OgWAAr.log
*** Downloading binary-only framework test at "file:///Users/<username>/carthage_binary_bug/test.json"
A shell task (/usr/bin/env unzip -uo -qq -d /var/folders/z3/lyh75tws0hg4nsp2wrg6gxnw0000gq/T/carthage-archive.559JOD /Users/<username>/Library/Caches/org.carthage.CarthageKit/binaries/test/1.0.0/test.zip) failed with exit code 9:
[/Users/<username>/Library/Caches/org.carthage.CarthageKit/binaries/tes …
```
> Remove the cache if unarchiving was failed

- README.md
I notice that Carthage 0.35.0 does not build with Xcode 9.4.1:
```
error: package at '/opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_devel_carthage/carthage/work/Carthage-0.35.0' requires a minimum Swift tools version of 4.2.0 (currently 4.1.0)
```
My guess is the requirement was raised by #2797, and that the README should reflect this new requirement. Not sure if similar changes should be made elsewhere.
> Update README to reflect the build requirements

- Source/CarthageKit/Xcode.swift
`FileManager.replaceItem(_:withItemAt:backupItemName:options:)` does not work if the source and destination are on different volumes. This fix checks that the source and dest are on the different volumes and falls back to using `FileManager.copyItem(at:to:)` if that is the case.
> Don't use replaceItem if source and dest are on different filesystems. Fixes #3003

- Source/CarthageKit/VersionFile.swift
Carthage will flag cached binary frameworks as invalid if they are built with a different version of the Swift, even if both the binary  and the local version of Swift are module stable. This was likely just missed when module stability support was added in https://github.com/Carthage/Carthage/pull/2902.
A simple example to show the issue (this assumes you are running Xcode 11.6, or any version of Swift that **isnt** 5.2.2):
```
echo "binary \"https://zendesk.jfrog.io/zendesk/libs-releases-local/ios/zendesk/ChatSDK/ChatSDK.json\" == 2.7.0" > Cartfile
carthage bootstrap --platform iOS --cache-builds
carthage bootstrap --platform iOS --cache-builds
```
Looking at the console output of the second run of `carthage bootstrap` shows that the cache has been marked as invalid and is subsequently …
> prevent re-downloading module stable binaries

- Source/CarthageKit/GitHub.swift
- Source/CarthageKit/Project.swift
- Source/CarthageKit/Proxy.swift
- Tests/CarthageKitTests/ProxyTests.swift
* As support for http_proxy/https_proxy environment already exists, there was also a need to support the no_proxy/NO_PROXY override.
* `kCFNetworkProxiesExceptionsList` is available only on macOS, hence the conditional statements.
* Made sure that downloaded binaries also use proxied environment, which was not the case.
* Moved `URLSession.proxiedSession` into Proxy.swift where it seems to belong a bit more.
> Support no_proxy/NO_PROXY environment variables

- Source/carthage/CopyFrameworks.swift
This PR should fix #2956 
I'm not a Swift developer so I'm not sure this is the proper way to write this code. 
This PR makes sure that we intersect VALID_ARCHS and ARCHS so we only keep the ARCHS that we are actually building.
> Attempt to remove invalid archs by intersecting VALID_ARCHS and ARCHS

- Documentation/Xcode12Workaround.md
Apple Silicon was written like this "Sillicon". This is fixed now.
> Fix Apple Silicon Typo in Xcode12Workaround.md

- Source/CarthageKit/CarthageKitVersion.swift
- Source/CarthageKit/Xcode.swift
This is a companion release to #3106. It cherry-picks the VALIDATE_WORKSPACE fix (https://github.com/Carthage/Carthage/commit/388482045d3452b7fc87a926d35181a614710e63) onto 0.36.0. The goal here is to give users something to fall back on if the xcframeworks release causes problems.
> v0.36.1, everything new _except_ for xcframeworks

- Source/CarthageKit/XCDBLDExtensions.swift
- Source/CarthageKit/Xcode.swift
In large repos (repos with many xcode projects in them, or repos with deeply nested directories), `buildableSchemesInDirectory` can become noticeably slow.
This change makes the directory enumerator stop descending when we filter out a URL, and calls `xcodebuild -list` concurrently using the same pattern that Carthage uses further down.
> Locate schemes concurrently

- Source/CarthageKit/Xcode.swift
Projects with Cartfile dependencies typically contain a FRAMEWORKS_SEARCH_PATH entry like `Carthage/Build/iOS`. With `--use-xcframeworks`, that platform-specific folder ("iOS") might not exist. This makes the [predicate in extractXCFrameworks](https://github.com/Carthage/Carthage/blob/0668de43eb5d323d2e816eaab83677f50a8eeb24/Source/CarthageKit/Xcode.swift#L838) fail, because resolvingSymlinksInPath() has [realpath(3) semantics](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/realpath.3.html) and will not resolve symlinks for a non-existant path.
Fixed by truncating the given URL down to its extant portion. Since we only care about matching the prefix, and since the `Carthage/Build` directory should always exist because …
> Fix xcframework extraction when a project refers to a missing build directory

- Documentation/Artifacts.md
- README.md
- Source/CarthageKit/BinaryProject.swift
- Source/CarthageKit/CarthageKitVersion.swift
- Source/CarthageKit/Constants.swift
- Source/CarthageKit/Project.swift
- Source/carthage/Extensions.swift
- Tests/CarthageKitTests/BinaryProjectSpec.swift
- Tests/CarthageKitTests/ProjectSpec.swift
Bumps version to 0.38.0
Small behavior change that came up while working on release notes for #3123: Currently, Carthage will only download prebuilt assets whose names contain `.framework`. Now, it'll also download assets whose names  `.xcframework`. If a release has both framework and xcframework assets, it'll choose which set to download based the --use-xcframeworks flag.
> Release: v0.38.0

- README.md
Thanks for the mention, but Alamofire 4 is no longer recommended, so this PR update the README to use Alamofire 5 in the example.
> Use modern Alamofire version in README

- Source/CarthageKit/Xcode.swift
- Source/XCDBLD/XcodeVersion.swift
- Tests/XCDBLDTests/XcodeVersionSpec.swift
> Fix issue where Carthage doesn’t build for watchOS or tvOS if bitcode is disabled in Xcode 14

- Source/CarthageKit/CarthageKitVersion.swift
Bump up the version to 0.39.0 for the next release.
Diff : https://github.com/Carthage/Carthage/compare/0.38.0...a91d086ceaffef65c4a4a761108f3f32c519940c
This version includes #3293. It's important to fix watchOS and tvOS support on Xcode 14.
@Carthage/carthage 
It looks like no one has maintained it recently, So I'd like to release a newer version.
Could anyone who lives take a look at this PR?
> Bump up version to 0.39.0

- Source/CarthageKit/BuildSettings.swift
- Source/CarthageKit/Simulator.swift
- Source/CarthageKit/VersionFile.swift
- Source/XCDBLD/SDK.swift
- Source/carthage/Archive.swift
- Source/carthage/Build.swift
• Move `selectAvailableSimulator` to a new query method `sdk.simulatorJsonKeyUnderDevicesDictQuery`
• Add knownIn2023Year APIs.
• Fix some whitespace that had spaces in a tabs-based file.
This should fix #3344
> Support visionOS by using `-destination xros/xrsimulator`. Make additive changes to XCBLD’s SDK.

- Makefile
- script/copy-fixtures
- script/strings_of_xcrun_find_ld.zsh
_[This does not affect the runtime behavior of Carthage. Just compilation of 'Carthage as a tool itself.']_
If the new linker is there, then `dirname $(xcrun --find swift))/../lib/swift_static/macosx` should not be respected as the sentinel value it held in pre-«Xcode 15» days.
In the Makefile, we look for `'^only one snapshot supported'` (which only exists in the old linker) to tell us the old linker is present.
See <https://github.com/apple-opensource/ld64/blame/8568ce3517546665f1f9e0f7ba1858889a305454/src/ld/Snapshot.cpp> for the old linker. 
See <https://github.com/apple-oss-distributions/dyld/> for the new linker.
Closes <https://github.com/Carthage/Carthage/issues/3348>.
> Fix Makefile to only pass `-static-stdlib` to `swiftc` when the old linker is `xcrun --find ld` returned.

- Source/CarthageKit/MachHeader.swift
Fix typo: endianess -> endianness
> Fix endianness typo in MachHeader unused computed property internal to CarthageKit.
